#!/bin/bash
echo "Content-type: text/html"
echo ""
echo "<HTML>"
echo "<HEAD>"
echo "<TITLE>Date & Time...</TITLE>"
echo "</HEAD>"
echo "<BODY>"
echo -e "The date and time is: `date`"
echo "</BODY>"
echo "</HTML>"