package core.interop;


/**
* core/interop/Appointment.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Calendar.idl
* Sunday, April 10, 2005 10:19:45 PM CEST
*/

public final class Appointment implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public core.interop.Date startDate = null;
  public core.interop.Date endDate = null;
  public String location = null;
  public String description = null;
  public boolean isGroupAppointment = false;

  public Appointment ()
  {
  } // ctor

  public Appointment (int _id, core.interop.Date _startDate, core.interop.Date _endDate, String _location, String _description, boolean _isGroupAppointment)
  {
    id = _id;
    startDate = _startDate;
    endDate = _endDate;
    location = _location;
    description = _description;
    isGroupAppointment = _isGroupAppointment;
  } // ctor

} // class Appointment
