package core.interop;


/**
* core/interop/AppointmentsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Calendar.idl
* Sunday, April 10, 2005 10:19:45 PM CEST
*/

abstract public class AppointmentsHelper
{
  private static String  _id = "IDL:interoperability/Appointments:1.0";

  public static void insert (org.omg.CORBA.Any a, core.interop.Appointment[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static core.interop.Appointment[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = core.interop.AppointmentHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (core.interop.AppointmentsHelper.id (), "Appointments", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static core.interop.Appointment[] read (org.omg.CORBA.portable.InputStream istream)
  {
    core.interop.Appointment value[] = null;
    int _len0 = istream.read_long ();
    value = new core.interop.Appointment[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = core.interop.AppointmentHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, core.interop.Appointment[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      core.interop.AppointmentHelper.write (ostream, value[_i0]);
  }

}
