package core.interop;


/**
* core/interop/CalendarPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Calendar.idl
* Sunday, April 10, 2005 10:19:46 PM CEST
*/

public abstract class CalendarPOA extends org.omg.PortableServer.Servant
 implements core.interop.CalendarOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getAppointments", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // interoperability/Calendar/getAppointments
       {
         String loginName = in.read_string ();
         String password = in.read_string ();
         core.interop.Appointment $result[] = null;
         $result = this.getAppointments (loginName, password);
         out = $rh.createReply();
         core.interop.AppointmentsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:interoperability/Calendar:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Calendar _this() 
  {
    return CalendarHelper.narrow(
    super._this_object());
  }

  public Calendar _this(org.omg.CORBA.ORB orb) 
  {
    return CalendarHelper.narrow(
    super._this_object(orb));
  }


} // class CalendarPOA
