package core.interop;


/**
* core/interop/CalendarOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Calendar.idl
* Sunday, April 10, 2005 10:19:46 PM CEST
*/

public interface CalendarOperations 
{
  core.interop.Appointment[] getAppointments (String loginName, String password);
} // interface CalendarOperations
