package core.interop;

/**
* core/interop/CalendarHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Calendar.idl
* Sunday, April 10, 2005 10:19:46 PM CEST
*/

public final class CalendarHolder implements org.omg.CORBA.portable.Streamable
{
  public core.interop.Calendar value = null;

  public CalendarHolder ()
  {
  }

  public CalendarHolder (core.interop.Calendar initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = core.interop.CalendarHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    core.interop.CalendarHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return core.interop.CalendarHelper.type ();
  }

}
