package core.interop;

/**
* core/interop/DateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Calendar.idl
* Sunday, April 10, 2005 10:19:45 PM CEST
*/

public final class DateHolder implements org.omg.CORBA.portable.Streamable
{
  public core.interop.Date value = null;

  public DateHolder ()
  {
  }

  public DateHolder (core.interop.Date initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = core.interop.DateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    core.interop.DateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return core.interop.DateHelper.type ();
  }

}
