package StockObjects;

/**
* StockObjects/QuoteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StockObjects.idl
* Wednesday, April 6, 2005 9:18:31 PM CEST
*/

public final class QuoteHolder implements org.omg.CORBA.portable.Streamable
{
  public StockObjects.Quote value = null;

  public QuoteHolder ()
  {
  }

  public QuoteHolder (StockObjects.Quote initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StockObjects.QuoteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StockObjects.QuoteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StockObjects.QuoteHelper.type ();
  }

}
