package StockObjects;


/**
* StockObjects/StockPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StockObjects.idl
* Wednesday, April 6, 2005 9:18:31 PM CEST
*/

public abstract class StockPOA extends org.omg.PortableServer.Servant
 implements StockObjects.StockOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("get_quote", new java.lang.Integer (0));
    _methods.put ("set_quote", new java.lang.Integer (1));
    _methods.put ("_get_description", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Returns the current stock quote.
       case 0:  // StockObjects/Stock/get_quote
       {
         try {
           StockObjects.Quote $result = null;
           $result = this.get_quote ();
           out = $rh.createReply();
           StockObjects.QuoteHelper.write (out, $result);
         } catch (StockObjects.Unknown $ex) {
           out = $rh.createExceptionReply ();
           StockObjects.UnknownHelper.write (out, $ex);
         }
         break;
       }


  // Sets the current stock quote.
       case 1:  // StockObjects/Stock/set_quote
       {
         StockObjects.Quote stock_quote = StockObjects.QuoteHelper.read (in);
         this.set_quote (stock_quote);
         out = $rh.createReply();
         break;
       }


  // e.g. company name.
       case 2:  // StockObjects/Stock/_get_description
       {
         String $result = null;
         $result = this.description ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:StockObjects/Stock:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Stock _this() 
  {
    return StockHelper.narrow(
    super._this_object());
  }

  public Stock _this(org.omg.CORBA.ORB orb) 
  {
    return StockHelper.narrow(
    super._this_object(orb));
  }


} // class StockPOA
