package StockObjects;


/**
* StockObjects/StockOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StockObjects.idl
* Wednesday, April 6, 2005 9:18:31 PM CEST
*/

public interface StockOperations 
{

  // Returns the current stock quote.
  StockObjects.Quote get_quote () throws StockObjects.Unknown;

  // Sets the current stock quote.
  void set_quote (StockObjects.Quote stock_quote);

  // e.g. company name.
  String description ();
} // interface StockOperations
