package StockObjects;


/**
* StockObjects/StockFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StockObjects.idl
* Wednesday, April 6, 2005 9:18:31 PM CEST
*/

public interface StockFactoryOperations 
{
  StockObjects.Stock create_stock (String symbol, String description);
} // interface StockFactoryOperations
