package StockObjects;


/**
* StockObjects/Stock.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StockObjects.idl
* Wednesday, April 6, 2005 9:18:31 PM CEST
*/

public interface Stock extends StockOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Stock
