/**
 * Stores all contextual (non-local) information needed during the VM -> ASM translation.
 */
public class VMTranslationContext {

    private int autoGeneratedIndex = 0;

    public int getNextAutoGeneratedIndex() {
        if (autoGeneratedIndex < Integer.MAX_VALUE) {
            return autoGeneratedIndex++;
        } else {
            throw new VMTranslatorException("no more index values available");
        }
    }
}
