/* Generated By:JavaCC: Do not edit this line. BibTexQueryConstants.java */
package gw.query;

public interface BibTexQueryConstants {

  int EOF = 0;
  int AND_OP = 1;
  int OR_OP = 2;
  int OPERATOR = 3;
  int WORD = 4;
  int OPEN_PAR = 5;
  int CLOSE_PAR = 6;
  int OPEN_DEL = 7;
  int CLOSE_DEL = 8;
  int EOL = 9;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<AND_OP>",
    "<OR_OP>",
    "<OPERATOR>",
    "<WORD>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<EOL>",
    "\" \"",
    "\"\\t\"",
  };

}
