package gw.query;

import java.io.*;
import java.util.Map;

/** Helps us in implementing search methods other than the basic index search for
* certain fields.
*/
public interface SearchHandler
{
    /** Searches using the queryString, and giving a SearchResult that fits this
    * type of search.
    * @param parameterMap The map with all parameters for the search.
    * @return A SearchResult generated by the search
    * @throws IOException An error occured writing to the file system.
    */
    public SearchResult search(Map parameterMap) throws IOException;
}
