package gw.query;

import gw.storage.*;

import java.io.*;
import org.apache.lucene.document.*;

/** TopicSearch is an UpdateHandler that adds the topic into the document.
* This topic is generated by the PageInfo class.
*/
public class TopicSearch implements UpdateHandler
{
    /** Adds the topic field to the document.
    * @param storage The storage from which we can read the file.
    * @param file The file to read the topic from.
    * @param isDir Whether this file is really a file or a directory
    * @param doc The document to which we write the topics field.
    */
    public void update(Storage storage, String file, boolean isDir, Document doc) throws IOException
    {
        PageInfo info = new PageInfo(storage, file);
        doc.add(Field.Text("topic", info.getTopics()));
    }
}
