package client.interop;


/**
* client/interop/CalendarHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Calendar.idl
* Sunday, April 10, 2005 10:45:06 PM CEST
*/

abstract public class CalendarHelper
{
  private static String  _id = "IDL:interoperability/Calendar:1.0";

  public static void insert (org.omg.CORBA.Any a, client.interop.Calendar that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static client.interop.Calendar extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (client.interop.CalendarHelper.id (), "Calendar");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static client.interop.Calendar read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CalendarStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, client.interop.Calendar value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static client.interop.Calendar narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof client.interop.Calendar)
      return (client.interop.Calendar)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      client.interop._CalendarStub stub = new client.interop._CalendarStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
