package client.interop;


/**
* client/interop/CalendarOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Calendar.idl
* Sunday, April 10, 2005 10:45:06 PM CEST
*/

public interface CalendarOperations 
{
  client.interop.Appointment[] getAppointments (String loginName, String password);
} // interface CalendarOperations
