/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#define ORBIT_IDL_C_COMMON
#define Calendar_COMMON
#include "Calendar.h"

static const CORBA_unsigned_long ORBit_zero_int = 0;

#ifndef ORBIT_IDL_C_IMODULE_Calendar
void _ORBIT_skel_small_interoperability_Calendar_getAppointments(POA_interoperability_Calendar             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
interoperability_Appointments* (*_impl_getAppointments)(PortableServer_Servant _servant, const CORBA_char * loginName, const CORBA_char * password, CORBA_Environment *ev)) {
*(interoperability_Appointments* *)_o_retval = _impl_getAppointments (_o_servant, *(const CORBA_char * *)_o_args[0], *(const CORBA_char * *)_o_args[1], _o_ev);
}

#endif
#if ( (TC_IMPL_TC_interoperability_Date_0 == 'C') \
&& (TC_IMPL_TC_interoperability_Date_1 == 'a') \
&& (TC_IMPL_TC_interoperability_Date_2 == 'l') \
&& (TC_IMPL_TC_interoperability_Date_3 == 'e') \
&& (TC_IMPL_TC_interoperability_Date_4 == 'n') \
&& (TC_IMPL_TC_interoperability_Date_5 == 'd') \
&& (TC_IMPL_TC_interoperability_Date_6 == 'a') \
&& (TC_IMPL_TC_interoperability_Date_7 == 'r') \
) && !defined(TC_DEF_TC_interoperability_Date)
#define TC_DEF_TC_interoperability_Date 1
static const char *anon_subnames_array0[] = {"second", "minute", "hour", "day", "month", "year"};
static CORBA_TypeCode anon_subtypes_array1[] = {(CORBA_TypeCode)&TC_CORBA_long_struct, (CORBA_TypeCode)&TC_CORBA_long_struct, (CORBA_TypeCode)&TC_CORBA_long_struct, (CORBA_TypeCode)&TC_CORBA_long_struct, (CORBA_TypeCode)&TC_CORBA_long_struct, (CORBA_TypeCode)&TC_CORBA_long_struct};
#ifdef ORBIT_IDL_C_IMODULE_Calendar
static
#endif
struct CORBA_TypeCode_struct TC_interoperability_Date_struct = {
{&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
CORBA_tk_struct,
0,
0,
ORBIT_ALIGNOF_CORBA_LONG,
0,
6
,
(CORBA_TypeCode *)anon_subtypes_array1,
CORBA_OBJECT_NIL,
"Date",
"IDL:interoperability/Date:1.0",
(char **)anon_subnames_array0,
NULL,
-1,
0,
0, 0
};
#endif
#if ( (TC_IMPL_TC_interoperability_Appointment_0 == 'C') \
&& (TC_IMPL_TC_interoperability_Appointment_1 == 'a') \
&& (TC_IMPL_TC_interoperability_Appointment_2 == 'l') \
&& (TC_IMPL_TC_interoperability_Appointment_3 == 'e') \
&& (TC_IMPL_TC_interoperability_Appointment_4 == 'n') \
&& (TC_IMPL_TC_interoperability_Appointment_5 == 'd') \
&& (TC_IMPL_TC_interoperability_Appointment_6 == 'a') \
&& (TC_IMPL_TC_interoperability_Appointment_7 == 'r') \
) && !defined(TC_DEF_TC_interoperability_Appointment)
#define TC_DEF_TC_interoperability_Appointment 1
static const char *anon_subnames_array3[] = {"id", "startDate", "endDate", "location", "description", "isGroupAppointment"};
static CORBA_TypeCode anon_subtypes_array4[] = {(CORBA_TypeCode)&TC_CORBA_long_struct, (CORBA_TypeCode)&TC_interoperability_Date_struct, (CORBA_TypeCode)&TC_interoperability_Date_struct, (CORBA_TypeCode)&TC_CORBA_string_struct, (CORBA_TypeCode)&TC_CORBA_string_struct, (CORBA_TypeCode)&TC_CORBA_boolean_struct};
#ifdef ORBIT_IDL_C_IMODULE_Calendar
static
#endif
struct CORBA_TypeCode_struct TC_interoperability_Appointment_struct = {
{&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
CORBA_tk_struct,
0,
0,
MAX (ORBIT_ALIGNOF_CORBA_CHAR, MAX (ORBIT_ALIGNOF_CORBA_POINTER, MAX (ORBIT_ALIGNOF_CORBA_LONG, 1))),
0,
6
,
(CORBA_TypeCode *)anon_subtypes_array4,
CORBA_OBJECT_NIL,
"Appointment",
"IDL:interoperability/Appointment:1.0",
(char **)anon_subnames_array3,
NULL,
-1,
0,
0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_interoperability_Appointment_0 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_interoperability_Appointment_1 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_interoperability_Appointment_2 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_interoperability_Appointment_3 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_interoperability_Appointment_4 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_interoperability_Appointment_5 == 'd') \
&& (TC_IMPL_TC_CORBA_sequence_interoperability_Appointment_6 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_interoperability_Appointment_7 == 'r') \
) && !defined(TC_DEF_TC_CORBA_sequence_interoperability_Appointment)
#define TC_DEF_TC_CORBA_sequence_interoperability_Appointment 1
static CORBA_TypeCode anon_subtypes_array7[] = {(CORBA_TypeCode)&TC_interoperability_Appointment_struct};
#ifdef ORBIT_IDL_C_IMODULE_Calendar
static
#endif
struct CORBA_TypeCode_struct TC_CORBA_sequence_interoperability_Appointment_struct = {
{&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
CORBA_tk_sequence,
0,
0,
MAX (ORBIT_ALIGNOF_CORBA_POINTER, MAX (ORBIT_ALIGNOF_CORBA_LONG, MAX (ORBIT_ALIGNOF_CORBA_STRUCT, 1))),
0,
1
,
(CORBA_TypeCode *)anon_subtypes_array7,
CORBA_OBJECT_NIL,
NULL,
NULL,
NULL,
NULL,
-1,
0,
0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_interoperability_Appointment_0 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_interoperability_Appointment_1 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_interoperability_Appointment_2 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_interoperability_Appointment_3 == 'e') \
&& (TC_IMPL_TC_CORBA_sequence_interoperability_Appointment_4 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_interoperability_Appointment_5 == 'd') \
&& (TC_IMPL_TC_CORBA_sequence_interoperability_Appointment_6 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_interoperability_Appointment_7 == 'r') \
) && !defined(TC_DEF_TC_CORBA_sequence_interoperability_Appointment)
#define TC_DEF_TC_CORBA_sequence_interoperability_Appointment 1
static CORBA_TypeCode anon_subtypes_array14[] = {(CORBA_TypeCode)&TC_interoperability_Appointment_struct};
#ifdef ORBIT_IDL_C_IMODULE_Calendar
static
#endif
struct CORBA_TypeCode_struct TC_CORBA_sequence_interoperability_Appointment_struct = {
{&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
CORBA_tk_sequence,
0,
0,
MAX (ORBIT_ALIGNOF_CORBA_POINTER, MAX (ORBIT_ALIGNOF_CORBA_LONG, MAX (ORBIT_ALIGNOF_CORBA_STRUCT, 1))),
0,
1
,
(CORBA_TypeCode *)anon_subtypes_array14,
CORBA_OBJECT_NIL,
NULL,
NULL,
NULL,
NULL,
-1,
0,
0, 0
};
#endif
#if ( (TC_IMPL_TC_interoperability_Appointments_0 == 'C') \
&& (TC_IMPL_TC_interoperability_Appointments_1 == 'a') \
&& (TC_IMPL_TC_interoperability_Appointments_2 == 'l') \
&& (TC_IMPL_TC_interoperability_Appointments_3 == 'e') \
&& (TC_IMPL_TC_interoperability_Appointments_4 == 'n') \
&& (TC_IMPL_TC_interoperability_Appointments_5 == 'd') \
&& (TC_IMPL_TC_interoperability_Appointments_6 == 'a') \
&& (TC_IMPL_TC_interoperability_Appointments_7 == 'r') \
) && !defined(TC_DEF_TC_interoperability_Appointments)
#define TC_DEF_TC_interoperability_Appointments 1
static CORBA_TypeCode anon_subtypes_array17[] = {(CORBA_TypeCode)&TC_CORBA_sequence_interoperability_Appointment_struct};
#ifdef ORBIT_IDL_C_IMODULE_Calendar
static
#endif
struct CORBA_TypeCode_struct TC_interoperability_Appointments_struct = {
{&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
CORBA_tk_alias,
0,
0,
MAX (ORBIT_ALIGNOF_CORBA_POINTER, MAX (ORBIT_ALIGNOF_CORBA_LONG, MAX (ORBIT_ALIGNOF_CORBA_STRUCT, 1))),
0,
1
,
(CORBA_TypeCode *)anon_subtypes_array17,
CORBA_OBJECT_NIL,
"Appointments",
"IDL:interoperability/Appointments:1.0",
NULL,
NULL,
-1,
0,
0, 0
};
#endif
#if ( (TC_IMPL_TC_interoperability_Calendar_0 == 'C') \
&& (TC_IMPL_TC_interoperability_Calendar_1 == 'a') \
&& (TC_IMPL_TC_interoperability_Calendar_2 == 'l') \
&& (TC_IMPL_TC_interoperability_Calendar_3 == 'e') \
&& (TC_IMPL_TC_interoperability_Calendar_4 == 'n') \
&& (TC_IMPL_TC_interoperability_Calendar_5 == 'd') \
&& (TC_IMPL_TC_interoperability_Calendar_6 == 'a') \
&& (TC_IMPL_TC_interoperability_Calendar_7 == 'r') \
) && !defined(TC_DEF_TC_interoperability_Calendar)
#define TC_DEF_TC_interoperability_Calendar 1
#ifdef ORBIT_IDL_C_IMODULE_Calendar
static
#endif
struct CORBA_TypeCode_struct TC_interoperability_Calendar_struct = {
{&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
CORBA_tk_objref,
0,
0,
ORBIT_ALIGNOF_CORBA_POINTER,
0,
0
,
NULL,
CORBA_OBJECT_NIL,
"Calendar",
"IDL:interoperability/Calendar:1.0",
NULL,
NULL,
-1,
0,
0, 0
};
#endif

#ifndef ORBIT_IDL_C_IMODULE_Calendar
CORBA_unsigned_long interoperability_Calendar__classid = 0;
#endif

/* Interface type data */

static ORBit_IArg interoperability_Calendar_getAppointments__arginfo [] = {
	{ TC_CORBA_string,  ORBit_I_ARG_IN , "loginName" },
	{ TC_CORBA_string,  ORBit_I_ARG_IN , "password" }
};

#ifdef ORBIT_IDL_C_IMODULE_Calendar
static
#endif
ORBit_IMethod interoperability_Calendar__imethods [] = {
	{
		{ 2, 2, interoperability_Calendar_getAppointments__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		TC_interoperability_Appointments, "getAppointments", 15,
		0
}
};static CORBA_string interoperability_Calendar__base_itypes[] = {
"IDL:omg.org/CORBA/Object:1.0"
};
#ifdef ORBIT_IDL_C_IMODULE_Calendar
static
#endif
ORBit_IInterface interoperability_Calendar__iinterface = {
TC_interoperability_Calendar,{1, 1, interoperability_Calendar__imethods, FALSE},
{1, 1, interoperability_Calendar__base_itypes, FALSE}
};

