/* Generated by Together */
import java.io.Serializable;

public interface AFAgent {
    void addAFBehaviour(AFBehaviour behavior);

    void removeAFBehavior(AFBehaviour behavior);

    void send(AFMessage message);

    void receive();

    AFMessage blockingReceive();

    AFMessage blockingReceive(long millis);

    AFAgentID afAgentID();
}
