/* Generated by Together */

public class AFBehaviour {
    /**
     * returns false if method is restarted and the behavior cannot be restarted, i.e. canBeRestarted returns false 
     */
    public boolean start() {
    }

    public void stop() {
    }

    public boolean canBeRestarted() {
    }

    public boolean IsStarted() {
    }

    public void SetAgent(AFAgent agent) {
    }

    public boolean hasRun() {
    }

    public void SetName(String name) {
    }

    public String GetName() {
    }
}
