/* Generated by Together */
import AFAgentID;
import java.lang.String;

public interface AFMessage {
    String GetContent();

    AFAgentID GetSender();

    AFAgentID GetReceiver();

    void SetContent(String content);

    void SetSender(AFAgentID sender);

    void SetReceiver(AFAgentID receiver);

    void SetPerformative(int performative);

    int GetPerformative();
}
