/* Generated by Together */
import java.net.URL;

public class AgletLocation implements AFLocation {
    public URL GetURL() {
    }

    public void SetURL(URL url) {
    }

    private URL url;
}
