/* Generated by Together */
import java.util.Collection;

public class ItineraryBehaviour extends SingleBehaviour {
    public ItineraryBehaviour(int timePeriod, Collection objectives) {
    }

    public void SetMissBehavior(ObjectiveMissedBehaviour missBehavior) {
    }
}
