/* Generated by Together */

public class Objective {
    public Objective(AFLocation location, int earliest, int latest) {
    }

    public AFLocation GetLocation() {
    }

    public int GetEarliest() {
    }

    public int GetLatest() {
    }
}
