#!/bin/bash

echo
echo "*************************************************"
echo

latex ./diploma.tex

echo
echo "*************************************************"
echo

latex ./diploma.tex

echo
echo "*************************************************"
echo

latex ./diploma.tex
