Program pian;
uses crt;
var c:char;
begin
 clrscr;
 writeln;
 repeat
  c:=readkey;
  case c of
   'z':
      begin
       sound(262);
       delay(850);
       nosound;
      end;
   'x':
      begin
       sound(294);
       delay(850);
       nosound;
      end;
   'c':
      begin
       sound(330);
       delay(850);
       nosound;
      end;
   'v':
      begin
       sound(350);
       delay(850);
       nosound;
      end;
   'b':
      begin
       sound(392);
       delay(850);
       nosound;
      end;
   'n':
      begin
       sound(440);
       delay(850);
       nosound;
      end;
   'm':
      begin
       sound(494);
       delay(850);
       nosound;
      end;
   'a':
      begin
       sound(524);
       delay(850);
       nosound;
      end;
   's':
      begin
       sound(588);
       delay(850);
       nosound;
      end;
   'd':
      begin
       sound(660);
       delay(850);
       nosound;
      end;
   'f':
      begin
       sound(700);
       delay(850);
       nosound;
      end;
   'g':
      begin
       sound(784);
       delay(850);
       nosound;
      end;
   'h':
      begin
       sound(880);
       delay(850);
       nosound;
      end;
   'j':
      begin
       sound(988);
       delay(850);
       nosound;
      end;
   'q':
      begin
       sound(1048);
       delay(850);
       nosound;
      end;
   'w':
      begin
       sound(1176);
       delay(850);
       nosound;
      end;
   'e':
      begin
       sound(1320);
       delay(850);
       nosound;
      end;
   'r':
      begin
       sound(1400);
       delay(850);
       nosound;
      end;
   't':
      begin
       sound(1568);
       delay(850);
       nosound;
      end;
   'y':
      begin
       sound(1760);
       delay(850);
       nosound;
      end;
   'u':
      begin
       sound(1976);
       delay(850);
       nosound;
      end;
  end;
 until c=#27;
 clrscr;
end.