PROGRAM OARECARE;
USES CRT,GRAPH;
CONST N=3;
VAR DRIVER,MOD_G,I,K,M:INTEGER;
    X:REAL;
BEGIN
DRIVER:=DETECT;
INITGRAPH(DRIVER,MOD_G,'C:\TP\BGI');
SETBKCOLOR(YELLOW);
X:=N*PI/256;
K:=(GETMAXY-100) DIV 2;
M:=GETMAXY DIV 2;
FOR I:=1 TO 256 DO
BEGIN
SETCOLOR(RANDOM(16));
DELAY(10);
LINE(M-ROUND(K*SIN(X*I)),I,I,M-ROUND(K*COS(X*I)));
END;
READKEY;
CLOSEGRAPH;
END.