Program formula_one;
uses crt, utilg, graph;
label 1,2,3,a1,sf1;
type sir=array[1..20] of string;
var i:integer;
    cuv:sir;
    id,a:byte;

Procedure formula(n,color:integer);
var x:integer;
begin
 setcolor(color);
 x:=n+40;
 circle(n,240,4);
 circle(n,240,6);
 circle(x,242,3);
 circle(x,242,5);
 line(n-7,243,n-9,243);
 line(n+7,243,x-6,243);
 line(x+6,243,x+15,243);
 line(n-9,243,n-7,230);
 line(n-7,230,n-8,228);
 line(n-8,228,n+4,234);
 line(n+5,237,n+20,237);
 line(n+20,237,n+10,235);
 line(n+6,235,n+6,235);
 line(n+6,234,n+20,234);
 ellipse(n+27,234,180,320,7,3);
 line(n+33,235,x+15,243);
 line(n-9,243,n-20,257);
 line(n-7,230,n-20,217);
 bar(n-656,217,n-20,257);
 rectangle(n-656,217,n-20,257);
end;

Procedure texte(x,y:integer;str:string;bk,c:word);
begin
 textbackground(bk);
 textcolor(c);
 gotoxy(x,y);
 write(str);
end;

Procedure cursor(x,y,lung:integer;c:word);
var i:integer;
begin
 textcolor(c);
 gotoxy(x,y);
 for i:=1 to lung do
  write(chr(219));
end;

Procedure meniu(cuv:sir;j:byte;var id:byte);
var i,lin:byte;
    ch:char;
begin
 clrscr;
 textcolor(lightgreen);
 gotoxy(26,6);
 write('Ú');write('ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ');write('¿');
 for i:=7 to j+6 do
  begin
   gotoxy(26,i);write('³');
   gotoxy(50,i);write('³');
  end;
 gotoxy(26,7+j);
 write('À');write('ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ');write('Ù');
 for i:=1 to j do
  texte(28,6+i,cuv[i],black,magenta);
 lin:=7;
 cursor(27,7,22,lightgray);
 texte(28,7,cuv[1],lightgray,black);
 repeat
  ch:=readkey;
  if ch=#80 then
             begin
              cursor(27,lin,22,black);
              texte(28,lin,cuv[lin-6],black,magenta);
              lin:=lin+1;
              if lin=j+7 then lin:=7;
              cursor(27,lin,22,lightgray);
              texte(28,lin,cuv[lin-6],lightgray,black);
             end;
  if ch=#72 then
             begin
              cursor(27,lin,22,black);
              texte(28,lin,cuv[lin-6],black,magenta);
              lin:=lin-1;
              if lin=6 then lin:=j+6;
              cursor(27,lin,22,lightgray);
              texte(28,lin,cuv[lin-6],lightgray,black);
             end;
 until ch=#13;
 id:=lin;
end;

Procedure schedule;
begin
 clrscr;
 gotoxy(1,2);
 write('Ú');
 for i:=2 to 79 do
  if i in [7,40,46] then write('Â')
                    else write('Ä');
 write('¿');
 for i:=3 to 23 do
  begin
   gotoxy(1,i);
   if i mod 2 = 1 then write('³')
                  else write('Ã');
   gotoxy(80,i);
   if i mod 2 = 1 then write('³')
                  else write('´');
   gotoxy(40,i);
   if i mod 2 = 1 then write('³')
                  else write('Å');
   gotoxy(7,i);
   if i mod 2 = 1 then write('³')
                  else write('Å');
   gotoxy(46,i);
   if i mod 2 = 1 then write('³')
                  else write('Å');
  end;
 gotoxy(1,24);
 write('À');
 for i:=2 to 79 do
  if i in [7,40,46] then write('Á')
                    else write('Ä');
 write('Ù');
 for i:=2 to 79 do
  if not (i in [7,40,46]) then
   begin
    gotoxy(i,2);
    write('Ä');
    gotoxy(i,4);
    write('Ä');
    gotoxy(i,6);
    write('Ä');
    gotoxy(i,8);
    write('Ä');
    gotoxy(i,10);
    write('Ä');
    gotoxy(i,12);
    write('Ä');
    gotoxy(i,14);
    write('Ä');
    gotoxy(i,16);
    write('Ä');
    gotoxy(i,18);
    write('Ä');
    gotoxy(i,20);
    write('Ä');
    gotoxy(i,22);
    write('Ä');
   end;
 textcolor(red);
 gotoxy(2,3);
 write('Date');
 gotoxy(8,3);
 write('    Location of the circiut ');
 gotoxy(41,3);
 write('Date');
 gotoxy(47,3);
 write('    Location of the circiut ');
 gotoxy(2,5);
 write('09.03');
 gotoxy(8,5);
 write(' Australia - Melbourne ');
 gotoxy(2,7);
 write('30.03');
 gotoxy(8,7);
 write(' Brazil - Interlagos ');
 gotoxy(2,9);
 write('13.04');
 gotoxy(8,9);
 write(' Argentina - Buenos Aires ');
 gotoxy(2,11);
 write('27.04');
 gotoxy(8,11);
 write(' San Marino - Imola ');
 gotoxy(2,13);
 write('11.05');
 gotoxy(8,13);
 write(' Monaco - Monte Carlo ');
 gotoxy(2,15);
 write('25.05');
 gotoxy(8,15);
 write(' Spain - Barcelona ');
 gotoxy(2,17);
 write('15.06');
 gotoxy(8,17);
 write(' Canada - Montreal ');
 gotoxy(2,19);
 write('29.06');
 gotoxy(8,19);
 write(' France - Magny Cours ');
 gotoxy(2,21);
 write('13.07');
 gotoxy(8,21);
 write(' England - Silverstone ');
 gotoxy(2,23);
 write('27.07');
 gotoxy(8,23);
 write(' Germany - Hockenheim ');
 gotoxy(41,5);
 write('10.08');
 gotoxy(47,5);
 write(' Hungary - Budapest ');
 gotoxy(41,7);
 write('24.08');
 gotoxy(47,7);
 write(' Belgium - Spa ');
 gotoxy(41,9);
 write('07.09');
 gotoxy(47,9);
 write(' Italy - Monza ');
 gotoxy(41,11);
 write('21.09');
 gotoxy(47,11);
 write(' Austry - A 1 Ring ');
 gotoxy(41,13);
 write('28.09');
 gotoxy(47,13);
 write(' Luembourg - Nurburgring ');
 gotoxy(41,15);
 write('12.10');
 gotoxy(47,15);
 write(' Japan - Suzuka ');
 gotoxy(41,17);
 write('26.10');
 gotoxy(47,17);
 write(' Portugal - Estoril ');
 gotoxy(20,25);
 write('Press "ENTER" to return to previous menu.');
 readln;
end;

Procedure chenar;
begin
 clrscr;
 textcolor(brown);
 gotoxy(1,2);
 write('Ú');
 for i:=2 to 79 do
  if i in [7,31,51,57,63,70] then write('Â')
                             else write('Ä');
 write('¿');
 for i:=3 to 23 do
  begin
   gotoxy(1,i);
   if i mod 2 = 1 then write('³')
                  else write('Ã');
   gotoxy(80,i);
   if i mod 2 = 1 then write('³')
                  else write('´');
   gotoxy(7,i);
   if i mod 2 = 1 then write('³')
                  else write('Å');
   gotoxy(31,i);
   if i mod 2 = 1 then write('³')
                  else write('Å');
   gotoxy(51,i);
   if i mod 2 = 1 then write('³')
                  else write('Å');
   gotoxy(57,i);
   if i mod 2 = 1 then write('³')
                  else write('Å');
   gotoxy(63,i);
   if i mod 2 = 1 then write('³')
                  else write('Å');
   gotoxy(70,i);
   if i mod 2 = 1 then write('³')
                  else write('Å');
  end;
 gotoxy(1,24);
 write('À');
 for i:=2 to 79 do
  if i in [7,31,51,57,63,70] then write('Á')
                             else write('Ä');
 write('Ù');
 for i:=2 to 79 do
  if not (i in [7,31,51,57,63,70]) then
   begin
    gotoxy(i,2);
    write('Ä');
    gotoxy(i,4);
    write('Ä');
    gotoxy(i,6);
    write('Ä');
    gotoxy(i,8);
    write('Ä');
    gotoxy(i,10);
    write('Ä');
    gotoxy(i,12);
    write('Ä');
    gotoxy(i,14);
    write('Ä');
    gotoxy(i,16);
    write('Ä');
    gotoxy(i,18);
    write('Ä');
    gotoxy(i,20);
    write('Ä');
    gotoxy(i,22);
    write('Ä');
   end;
end;

Procedure pilots_teams;
begin
 chenar;
 gotoxy(1,2);
 textcolor(red);
 gotoxy(2,3);
 write(' Nr. ');
 gotoxy(8,3);
 write(' Name of the Pilot ');
 gotoxy(32,3);
 write(' Team ');
 gotoxy(52,3);
 write(' Age ');
 gotoxy(58,3);
 write(' GPs ');
 gotoxy(64,3);
 write(' Wins ');
 gotoxy(71,3);
 write(' Poles ');
 gotoxy(2,5);
 write('  1');
 gotoxy(8,5);
 write(' Damon Hill ');
 gotoxy(32,5);
 write(' Arrows Yamaha ');
 gotoxy(52,5);
 write(' 36 ');
 gotoxy(58,5);
 write(' 67 ');
 gotoxy(64,5);
 write(' 21 ');
 gotoxy(71,5);
 write(' 20 ');
 gotoxy(2,7);
 write('  2');
 gotoxy(8,7);
 write(' Pedro Diniz ');
 gotoxy(32,7);
 write(' Arrows Yamaha ');
 gotoxy(52,7);
 write(' 26 ');
 gotoxy(58,7);
 write(' 33 ');
 gotoxy(64,7);
 write(' 0 ');
 gotoxy(71,7);
 write(' 0 ');
 gotoxy(2,9);
 write('  3');
 gotoxy(8,9);
 write(' Jacques Villeneuve ');
 gotoxy(32,9);
 write(' Williams Renault ');
 gotoxy(52,9);
 write(' 25 ');
 gotoxy(58,9);
 write(' 16 ');
 gotoxy(64,9);
 write(' 4 ');
 gotoxy(71,9);
 write(' 3 ');
 gotoxy(2,11);
 write('  4');
 gotoxy(8,11);
 write(' Heinz-Harald Frentzen ');
 gotoxy(32,11);
 write(' Williams Renault ');
 gotoxy(52,11);
 write(' 29 ');
 gotoxy(58,11);
 write(' 48 ');
 gotoxy(64,11);
 write(' 0 ');
 gotoxy(71,11);
 write(' 0 ');
 gotoxy(2,13);
 write('  5');
 gotoxy(8,13);
 write(' Michael Schumacher ');
 gotoxy(32,13);
 write(' Ferrari ');
 gotoxy(52,13);
 write(' 28 ');
 gotoxy(58,13);
 write(' 85 ');
 gotoxy(64,13);
 write(' 22');
 gotoxy(71,13);
 write(' 14');
 gotoxy(2,15);
 write('  6');
 gotoxy(8,15);
 write(' Eddie Irvine ');
 gotoxy(32,15);
 write(' Ferrari ');
 gotoxy(52,15);
 write(' 31 ');
 gotoxy(58,15);
 write(' 48 ');
 gotoxy(64,15);
 write(' 0 ');
 gotoxy(71,15);
 write(' 0 ');
 gotoxy(2,17);
 write('  7');
 gotoxy(8,17);
 write(' Jean Alesi ');
 gotoxy(32,17);
 write(' Benetton Renault ');
 gotoxy(52,17);
 write(' 32 ');
 gotoxy(58,17);
 write(' 118');
 gotoxy(64,17);
 write(' 1 ');
 gotoxy(71,17);
 write(' 1 ');
 gotoxy(2,19);
 write('  8');
 gotoxy(8,19);
 write(' Gerhard Berger ');
 gotoxy(32,19);
 write(' Benetton Renault ');
 gotoxy(52,19);
 write(' 37 ');
 gotoxy(58,19);
 write(' 196');
 gotoxy(64,19);
 write(' 9 ');
 gotoxy(71,19);
 write(' 11');
 gotoxy(2,21);
 write('  9');
 gotoxy(8,21);
 write(' Mika Hakkinen ');
 gotoxy(32,21);
 write(' McLaren Mercedes ');
 gotoxy(52,21);
 write(' 28 ');
 gotoxy(58,21);
 write(' 79 ');
 gotoxy(64,21);
 write(' 0 ');
 gotoxy(71,21);
 write(' 0 ');
 gotoxy(2,23);
 write(' 10');
 gotoxy(8,23);
 write(' David Coulthard' );
 gotoxy(32,23);
 write(' McLaren Mercedes ');
 gotoxy(52,23);
 write(' 25 ');
 gotoxy(58,23);
 write(' 41 ');
 gotoxy(64,23);
 write(' 1 ');
 gotoxy(71,23);
 write(' 5 ');
 gotoxy(20,25);
 write('Press "ENTER" for the next pilots.');
 readln;
 chenar;
 textcolor(red);
 gotoxy(2,3);
 write(' Nr. ');
 gotoxy(8,3);
 write(' Name of the Pilot ');
 gotoxy(32,3);
 write(' Team ');
 gotoxy(52,3);
 write(' Age ');
 gotoxy(58,3);
 write(' GPs ');
 gotoxy(64,3);
 write(' Wins ');
 gotoxy(71,3);
 write(' Poles ');
 gotoxy(2,5);
 write(' 11');
 gotoxy(8,5);
 write(' Ralf Schumacher ');
 gotoxy(32,5);
 write(' Jordan Peugeot ');
 gotoxy(52,5);
 write(' 21 ');
 gotoxy(58,5);
 write(' 0 ');
 gotoxy(64,5);
 write(' 0 ');
 gotoxy(71,5);
 write(' 0 ');
 gotoxy(2,7);
 write(' 12');
 gotoxy(8,7);
 write(' Giancarlo Fisichella ');
 gotoxy(32,7);
 write(' Jordan Peugeot ');
 gotoxy(52,7);
 write(' 24 ');
 gotoxy(58,7);
 write(' 8 ');
 gotoxy(64,7);
 write(' 0 ');
 gotoxy(71,7);
 write(' 0 ');
 gotoxy(2,9);
 write(' 14');
 gotoxy(8,9);
 write(' Olivier Panis ');
 gotoxy(32,9);
 write(' Prost-Mugen Honda ');
 gotoxy(52,9);
 write(' 30 ');
 gotoxy(58,9);
 write(' 49 ');
 gotoxy(64,9);
 write(' 1 ');
 gotoxy(71,9);
 write(' 0 ');
 gotoxy(2,11);
 write(' 15');
 gotoxy(8,11);
 write(' Shinji Nakano ');
 gotoxy(32,11);
 write(' Prost-Mugen Honda ');
 gotoxy(52,11);
 write(' 25 ');
 gotoxy(58,11);
 write(' 0 ');
 gotoxy(64,11);
 write(' 0 ');
 gotoxy(71,11);
 write(' 0 ');
 gotoxy(2,13);
 write(' 16');
 gotoxy(8,13);
 write(' Johnny Herbert ');
 gotoxy(32,13);
 write(' Sauber Petronas ');
 gotoxy(52,13);
 write(' 32 ');
 gotoxy(58,13);
 write(' 96 ');
 gotoxy(64,13);
 write(' 2 ');
 gotoxy(71,13);
 write(' 0 ');
 gotoxy(2,15);
 write(' 17');
 gotoxy(8,15);
 write(' Nicola Larini ');
 gotoxy(32,15);
 write(' Sauber Petronas ');
 gotoxy(52,15);
 write(' 32 ');
 gotoxy(58,15);
 write(' 44 ');
 gotoxy(64,15);
 write(' 0 ');
 gotoxy(71,15);
 write(' 0 ');
 gotoxy(2,17);
 write(' 18');
 gotoxy(8,17);
 write(' Jos Verstappen ');
 gotoxy(32,17);
 write(' Tyrrell Ford ');
 gotoxy(52,17);
 write(' 24 ');
 gotoxy(58,17);
 write(' 31 ');
 gotoxy(64,17);
 write(' 0 ');
 gotoxy(71,17);
 write(' 0 ');
 gotoxy(2,19);
 write(' 19');
 gotoxy(8,19);
 write(' Mika Salo ');
 gotoxy(32,19);
 write(' Tyrrell Ford ');
 gotoxy(52,19);
 write(' 24 ');
 gotoxy(58,19);
 write(' 35 ');
 gotoxy(64,19);
 write(' 0 ');
 gotoxy(71,19);
 write(' 0 ');
 gotoxy(2,21);
 write(' 20');
 gotoxy(8,21);
 write(' Ukyo Katayama ');
 gotoxy(32,21);
 write(' Minardi Hart ');
 gotoxy(52,21);
 write(' 33 ');
 gotoxy(58,21);
 write(' 78 ');
 gotoxy(64,21);
 write(' 0 ');
 gotoxy(71,21);
 write(' 0 ');
 gotoxy(2,23);
 write(' 21');
 gotoxy(8,23);
 write(' Jarno Trulli ');
 gotoxy(32,23);
 write(' Minardi Hart ');
 gotoxy(52,23);
 write(' 22 ');
 gotoxy(58,23);
 write(' 0 ');
 gotoxy(64,23);
 write(' 0 ');
 gotoxy(71,23);
 write(' 0 ');
 gotoxy(20,25);
 write('Press "ENTER" for the next pilots.');
 readln;
 chenar;
 window(1,12,80,25);
 clrscr;
 window(1,1,80,25);
 gotoxy(1,12);
 write('À');
 for i:=2 to 79 do
  if i in [7,31,51,57,63,70] then write('Á')
                             else write('Ä');
 write('Ù');
 textcolor(red);
 gotoxy(2,3);
 write(' Nr. ');
 gotoxy(8,3);
 write(' Name of the Pilot ');
 gotoxy(32,3);
 write(' Team ');
 gotoxy(52,3);
 write(' Age ');
 gotoxy(58,3);
 write(' GPs ');
 gotoxy(64,3);
 write(' Wins ');
 gotoxy(71,3);
 write(' Poles ');
 gotoxy(2,5);
 write(' 22');
 gotoxy(8,5);
 write(' Rubens Barrichello ');
 gotoxy(32,5);
 write(' Stewart Ford ');
 gotoxy(52,5);
 write(' 24 ');
 gotoxy(58,5);
 write(' 64');
 gotoxy(64,5);
 write(' 0 ');
 gotoxy(71,5);
 write(' 1 ');
 gotoxy(2,7);
 write(' 23');
 gotoxy(8,7);
 write(' Jan Magnussen ');
 gotoxy(32,7);
 write(' Stewart Ford ');
 gotoxy(52,7);
 write(' 23 ');
 gotoxy(58,7);
 write(' 1 ');
 gotoxy(64,7);
 write(' 0 ');
 gotoxy(71,7);
 write(' 0 ');
 gotoxy(2,9);
 write(' 23');
 gotoxy(8,9);
 write(' Ricardo Rosset ');
 gotoxy(32,9);
 write(' Lola Ford ');
 gotoxy(52,9);
 write(' 28 ');
 gotoxy(58,9);
 write(' 31 ');
 gotoxy(64,9);
 write(' 0 ');
 gotoxy(71,9);
 write(' 0 ');
 gotoxy(2,11);
 write(' 25');
 gotoxy(8,11);
 write(' Vincento Sospiri ');
 gotoxy(32,11);
 write(' Lola Ford ');
 gotoxy(52,11);
 write(' 30 ');
 gotoxy(58,11);
 write(' 0 ');
 gotoxy(64,11);
 write(' 0 ');
 gotoxy(71,11);
 write(' 0 ');
 gotoxy(20,25);
 write('Press "ENTER" to return to previous menu.');
 readln;
end;

Procedure atribuire;
begin
 cuv[1]:='INFORMATION ABOUT';
 cuv[2]:='QUALIFING TIMES';
 cuv[3]:='RACE RESULTS';
 cuv[4]:='FASTEST LAP';
 cuv[5]:='WINNERS';
 cuv[6]:='DRIVERS CHAMPIONSHIP';
 cuv[7]:='CONSTRUCTORS CHAMP.';
 cuv[8]:='PREVIOUS MENU';
end;

Procedure winners(x1,x2,x3:string);
begin
 ini;
 setbkcolor(yellow);
 setcolor(green);
 setfillstyle(solidfill,blue);
 bar3d(100,300,233,400,20,topon);
 bar3d(233,280,366,400,20,topon);
 bar3d(366,320,500,400,20,topon);
 setcolor(brown);
 settextstyle(1,horizdir,8);
 outtextxy(280,285,'1');
 settextstyle(1,horizdir,6);
 outtextxy(155,315,'2');
 settextstyle(1,horizdir,5);
 outtextxy(420,330,'3');
 setcolor(lightgray);
 ellipse(300,50,0,360,40,10);
 line(260,50,285,150);
 line(340,50,315,150);
 line(285,150,275,170);
 line(315,150,325,170);
 ellipse(300,170,180,360,25,5);
 ellipse(265,85,94,260,10,20);
 ellipse(335,85,282,88,10,20);
 line(263,105,275,115);
 line(337,105,325,115);
 setcolor(red);
 settextstyle(1,horizdir,1);
 outtextxy(288,60,'FIA');
 outtextxy(272,80,'WORLD');
 outtextxy(284,100,'CUP');
 settextstyle(0,horizdir,0);
 outtextxy(250,270,x1);
 outtextxy(117,290,x2);
 outtextxy(383,310,x3);
 settextstyle(1,horizdir,1);
 outtextxy(100,420,'Press "ENTER" to return to previous menu.');
 repeat
  sound(random(500));
  delay(1);
 until keypressed;
 nosound;
end;

Procedure australia;
label a1,sf;
var a:byte;
begin
 a1:
 clrscr;
 atribuire;
 meniu(cuv,8,a);
 textbackground(black);
 textcolor(red);
 clrscr;
 case a of
  7:
  begin
   gotoxy(10,4);
   write('Date of the competition this year : 09.03.1997');
   gotoxy(10,6);
   write('Track length : 5.269 Km');
   gotoxy(10,8);
   write('Number of laps : 58');
   gotoxy(10,10);
   write('Total length : 305.602 Km');
   gotoxy(10,12);
   write('First used by FIA in the World Championship : 1996');
  end;
  8:
  begin
   textcolor(blue);
   gotoxy(12,2);
   write('AUSTRALIAN GRAND PRIX - QUALIFING TIMES - 08.03.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' 1.  Jacques Villeneuve     Williams Renault   CAN   1:29:369');
   writeln(' 2.  Heinz-Harald Frentzen  Williams Renault   GER   1:31:123');
   writeln(' 3.  Michael Schumacher     Ferrari            GER   1:31:472');
   writeln(' 4.  David Coulthard        McLaren Mercedes   GBR   1:31:531');
   writeln(' 5.  Eddie Irvine           Ferrari            GBR   1:31:881');
   writeln(' 6.  Mika Hakkinen          McLaren Mercedes   FIN   1:31:971');
   writeln(' 7.  Johnny Herbert         Sauber Petronas    GBR   1:32:287');
   writeln(' 8.  Jean Alesi             Benetton Renault   FRA   1:32:593');
   writeln(' 9.  Olivier Panis          Prost-Mugen Honda  FRA   1:32:842');
   writeln('10.  Gerhard Berger         Benetton Renault   AUT   1:32:870');
   writeln('11.  Rubens Barrichello     Stewart Ford       BRA   1:33:075');
   writeln('12.  Ralf Schumacher        Jordan Peugeot     GER   1:33:130');
   writeln('13.  Nicola Larini          Sauber Petronas    ITA   1:33:327');
   writeln('14.  Giancarlo Fisichella   Jordan Peugeot     ITA   1:33:552');
   writeln('15.  Ukyo Katayama          Minardi Hart       JAP   1:33:798');
   writeln('16.  Shinji Nakano          Prost-Mugen Honda  JAP   1:33:989');
   writeln('17.  Jarno Trulli           Minardi Hart       ITA   1:34:120');
   writeln('18.  Mika Salo              Tyrrell Ford       FIN   1:34:429');
   writeln('19.  Jan Magnussen          Stewart Ford       DEN   1:34:623');
   writeln('20.  Damnon Hill            Arrows Yamaha      GBR   1:34:806');
   gotoxy(20,25);
   write('Press "ENTER" for the following places.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(12,2);
   write('AUSTRALIAN GRAND PRIX - QUALIFING TIMES - 08.03.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln('21.  Jos Verstappen         Tyrrell Ford       NED   1:34:943');
   writeln('22.  Pedro Diniz            Arrows Yamaha      BRA   1:35:972');
  end;
  9:
  begin
   textcolor(blue);
   gotoxy(12,2);
   write('AUSTRALIAN GRAND PRIX - RACE FINISHING TIMES - 08.03.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' 1.  David Coulthard        McLaren Mercedes   GBR   1h:30:28:718');
   writeln(' 2.  Michael Scumacher      Ferrari            GER        +20:046');
   writeln(' 3.  Mika Hakkinen          McLaren Mercedes   FIN        +22:177');
   writeln(' 4.  Gerhard Berger         Benetton Renault   AUT        +22:481');
   writeln(' 5.  Oliver Panis           Prost-Mugen Honda  FRA      +1:00:308');
   writeln(' 6.  Nicola Larini          Sauber Petronas    ITA      +1:36:040');
   writeln(' 7.  Shinji Nakano          Prost-Mugen Honda  JAP        +2 laps');
   writeln(' 8.  Heinz-Harald Frentzen  Williams Renault   GER        +3 laps');
   writeln(' 9.  Jarno Trulli           Minardi Hart       ITA        +3 laps');
   writeln('10.  Pedro Diniz            Arrows Yamaha      BRA        +4 laps');
   textcolor(blue);
   writeln;
   writeln('                           NOT CLASSIFIED');
   writeln;
   textcolor(red);
   writeln(' NC  Damon Hill             Arrows Yamaha      GBR     -');
   writeln(' NC  Jacques Villeneuve     Williams Renault   CAN     -');
   writeln(' NC  Eddie Irvine           Ferrari            GBR     -');
   writeln(' NC  Jean Alesi             Benetton Renault   FRA     -');
   writeln(' NC  Ralf Schumacher        Jordan Peugeot     GER     -');
   writeln(' NC  Giancarlo Fisichella   Jordan Peugeot     ITA     -');
   writeln(' NC  Johnny Herbert         Sauber Petronas    GBR     -');
   gotoxy(20,25);
   write('Press "ENTER" for the following places.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(12,2);
   write('AUSTRALIAN GRAND PRIX - RACE FINISHING TIMES - 08.03.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' NC  Jos Verstappen         Tyrrell Ford       NED     -');
   writeln(' NC  Mika Salo              Tyrrell Ford       FIN     -');
   writeln(' NC  Ukyo Katayama          Minardi Hart       JAP     -');
   writeln(' NC  Rubens Barrichello     Stewart Ford       BRA     -');
   writeln(' NC  Jan Magnussen          Stewart Ford       NED     -');
  end;
  10:
  begin
   gotoxy(10,4);
   write('Fastest lap : ');
   gotoxy(10,6);
   write('Heinz-Harald Frentzen   Williams Renault   1:30:385');
  end;
  11:
  begin
   winners('David Coulthard','Michael Schumacher','Mika Hakkinen');
   readln;
   closegraph;
   goto a1;
  end;
  12:
  begin
   textcolor(blue);
   gotoxy(15,4);
   write('DRIVERS C3HAMPIONSHIP - AFTER AUSTRALIAN GP');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. David Coluthard        10 points');
   gotoxy(20,7);
   write(' 2. Michael Schumacher      6 points');
   gotoxy(20,8);
   write(' 3. Mika Hakkinen           4 points');
   gotoxy(20,9);
   write(' 4. Gerhard Berger          3 points');
   gotoxy(20,10);
   write(' 5. Olivier Panis           2 points');
   gotoxy(20,11);
   write(' 6. Nicola Larini           1 point ');
   gotoxy(20,25);
   write('Press "ENTER" to view the overall classification.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(15,4);
   write('DRIVERS CHAMPIONSHIP - OVERALL');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. David Coluthard        10 points');
   gotoxy(20,7);
   write(' 2. Michael Schumacher      6 points');
   gotoxy(20,8);
   write(' 3. Mika Hakkinen           4 points');
   gotoxy(20,9);
   write(' 4. Gerhard Berger          3 points');
   gotoxy(20,10);
   write(' 5. Olivier Panis           2 points');
   gotoxy(20,11);
   write(' 6. Nicola Larini           1 point ');
  end;
  13:
  begin
   textcolor(blue);
   gotoxy(15,4);
   write('CONSTRUCTORS CHAMPIONSHIP - AFTER AUSTRALIAN GP');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. McLaren Mercedes   14 points');
   gotoxy(20,7);
   write(' 2. Ferrari             6 points');
   gotoxy(20,8);
   write(' 3. Benetton Renault    3 points');
   gotoxy(20,9);
   write(' 4. Prost-Mugen Honda   2 points');
   gotoxy(20,10);
   write(' 5. Sauber Petronas     1 point');
   gotoxy(20,25);
   write('Press "ENTER" to view the overall classification.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(15,4);
   write('CONSTRUCTORS CHAMPIONSHIP - OVERALL');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. McLaren Mercedes   14 points');
   gotoxy(20,7);
   write(' 2. Ferrari             6 points');
   gotoxy(20,8);
   write(' 3. Benetton Renault    3 points');
   gotoxy(20,9);
   write(' 4. Prost-Mugen Honda   2 points');
   gotoxy(20,10);
   write(' 5. Sauber Petronas     1 point');
  end;
  14:goto sf;
 end;
 gotoxy(20,25);
 write('Press "ENTER" to return to previous menu.');
 readln;
 goto a1;
 sf:
end;

Procedure brazilia;
label a1,sf;
var a:byte;
begin
 a1:
 clrscr;
 atribuire;
 meniu(cuv,8,a);
 textbackground(black);
 textcolor(red);
 clrscr;
 case a of
  7:
  begin
   gotoxy(10,4);
   write('Date of the competition this year : 30.03.1997');
   gotoxy(10,6);
   write('Track length : 4.325 Km');
   gotoxy(10,8);
   write('Number of laps : 71');
   gotoxy(10,10);
   write('Total length : 307.075 Km');
  end;
  8:
  begin
   textcolor(blue);
   gotoxy(12,2);
   write('BRAZILIAN GRAND PRIX - QUALIFING TIMES - 29.03.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' 1.  Jacques Villeneuve     Williams Renault   CAN   1:16:004');
   writeln(' 2.  Michael Schumacher     Ferrari            GER   1:16:594');
   writeln(' 3.  Gerhard Berger         Benetton Renault   AUT   1:16:644');
   writeln(' 4.  Mika Hakkinen          McLaren Mercedes   FIN   1:16:692');
   writeln(' 5.  Olivier Panis          Prost-Mugen Honda  FRA   1:16:756');
   writeln(' 6.  Jean Alesi             Benetton Renault   FRA   1:16:757');
   writeln(' 7.  Giancarlo Fisichella   Jordan Peugeot     ITA   1:16:912');
   writeln(' 8.  Heinz-Harald Frentzen  Williams Renault   GER   1:16:924');
   writeln(' 9.  Damon Hill             Arrows Yamaha      GBR   1:17:090');
   writeln('10.  Ralf Schumacher        Jordan Peugeot     GER   1:17:175');
   writeln('11.  Rubens Barrichello     Stewart Ford       BRA   1:17:259');
   writeln('12.  David Coulthard        McLaren Mercedes   GBR   1:17:262');
   writeln('13.  Johnny Herbert         Sauber Petronas    GBR   1:17:409');
   writeln('14.  Eddie Irvine           Ferrari            GBR   1:17:527');
   writeln('15.  Shijni Nakano          Prost-Mugen Honda  JAP   1:17:999');
   writeln('16.  Pedro Diniz            Arrows Yamaha      BRA   1:18:095');
   writeln('17.  Jarno Trulli           Minardi Hart       ITA   1:18:336');
   writeln('18.  Ukyo Katayama          Minardi Hart       JAP   1:18:557');
   writeln('19.  Nicola Larini          Sauber Petronas    ITA   1:18:644');
   writeln('20.  Jan Magnussen          Stewart Ford       DEN   1:18:773');
   gotoxy(20,25);
   write('Press "ENTER" for the following places.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(12,2);
   write('BRAZILIAN GRAND PRIX - QUALIFING TIMES - 29.03.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln('21.  Jos Verstappen         Tyrrell Ford       NED   1:18:885');
   writeln('22.  Mika Salo              Tyrrell Ford       FIN   1:19:274');
  end;
  9:
  begin
   textcolor(blue);
   gotoxy(12,2);
   write('BRAZILIAN GRAND PRIX - RACE FINISHING TIMES - 30.03.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' 1.  Jacques Villeneuve     Williams Renault   CAN   1h:36:06:990');
   writeln(' 2.  Gerhard Berger         Benetton Renault   AUT         +4:190');
   writeln(' 3.  Olivier Panis          Prost-Mugen Honda  FRA        +15:870');
   writeln(' 4.  Mika Hakkinen          McLaren Mercedes   FIN        +33:033');
   writeln(' 5.  Michael Schumacher     Ferrari            GER        +33:731');
   writeln(' 6.  Jean Alesi             Benetton Renault   FRA        +34:020');
   writeln(' 7.  Johnny Herbert         Sauber Petronas    GBR        +50:912');
   writeln(' 8.  Giancarlo Fisichella   Jordan Peugeot     ITA      +1:00:639');
   writeln(' 9.  Heinz-Harald Frentzen  Williams Renault   GER      +1:15:402');
   writeln('10.  David Coulthard        McLaren Mercedes   GBR         +1 lap');
   writeln('11.  Nicola Larini          Sauber Petronas    ITA         +1 lap');
   writeln('12.  Jarno Trulli           Minardi Hart       ITA         +1 lap');
   writeln('13.  Mika Salo              Tyrrell Ford       FIN         +1 lap');
   writeln('14.  Shinji Nakano          Prost-Mugen Honda  JAP         +1 lap');
   writeln('15.  Jos Verstappen         Tyrrell Ford       NED        +2 laps');
   writeln('16.  Eddie Irvine           Ferrari            GBR        +2 laps');
   writeln('17.  Damon Hill             Arrows Yamaha      GBR        +3 laps');
   writeln('18.  Ukyo Katayama          Minardi Hart       JAP        +5 laps');
   gotoxy(20,25);
   write('Press "ENTER" for the following places.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(12,2);
   write('BRAZILIAN GRAND PRIX - RACE FINISHING TIMES - 30.03.1997');
   textcolor(red);
   gotoxy(1,4);
   textcolor(blue);
   writeln('                           NOT CLASSIFIED');
   writeln;
   textcolor(red);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' NC  Pedro Diniz            Williams Renault   BRA     -');
   writeln(' NC  Ralf Scumacher         Jordan Peugeot     GER     -');
   writeln(' NC  Rubens Barrichello     Stewart Ford       BRA     -');
   writeln(' NC  Jan Magnussen          Stewart Ford       DEN     -');
  end;
  10:
  begin
   gotoxy(10,4);
   write('Fastest lap : ');
   gotoxy(10,6);
   write('Jacques Villeneuve      Williams Renault   1:18:367');
  end;
  11:
  begin
   winners('Jacques Villeneuve','Gerhard Berger','Olivier Panis');
   readln;
   closegraph;
   goto a1;
  end;
  12:
  begin
   textcolor(blue);
   gotoxy(15,4);
   write('DRIVERS CHAMPIONSHIP - AFTER BRAZILIAN GP');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. Jacques Villeneuve     10 points');
   gotoxy(20,7);
   write(' 2. Gerhard Berger          6 points');
   gotoxy(20,8);
   write(' 3. Olivier Panis           4 points');
   gotoxy(20,9);
   write(' 4. Mika Hakkinen           3 points');
   gotoxy(20,10);
   write(' 5. Michael Schumacher      2 points');
   gotoxy(20,11);
   write(' 6. Jean Alesi              1 point ');
   gotoxy(20,25);
   write('Press "ENTER" to view the overall classification.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(15,4);
   write('DRIVERS CHAMPIONSHIP - OVERALL');
   gotoxy(20,6);
   textcolor(red);
   write(' 1. Jacques Villeneuve     10 points');
   gotoxy(20,7);
   write('    David Coulthard        10 points');
   gotoxy(20,8);
   write(' 3. Gerhard Berger          9 points');
   gotoxy(20,9);
   write(' 4. Michael Schumacher      8 points');
   gotoxy(20,10);
   write(' 5. Mika Hakkinen           7 points');
   gotoxy(20,11);
   write(' 6. Olivier Panis           6 points');
   gotoxy(20,12);
   write(' 7. Jean Alesi              1 point ');
   gotoxy(20,13);
   write('    Nicola Larini           1 point ');
  end;
  13:
  begin
   textcolor(blue);
   gotoxy(15,4);
   write('CONSTRUCTORS CHAMPIONSHIP - AFTER BRAZILIAN GP');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. Williams Renault   10 points');
   gotoxy(20,7);
   write(' 2. Benneton Renault    7 points');
   gotoxy(20,8);
   write(' 3. Prost-Mugen Honda   4 points');
   gotoxy(20,9);
   write(' 4. McLaren Mercedes    3 points');
   gotoxy(20,10);
   write(' 5. Ferrari             1 point ');
   gotoxy(20,25);
   write('Press "ENTER" to view the overall classification.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(15,4);
   write('CONSTRUCTORS CHAMPIONSHIP - OVERALL');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. McLaren Mercedes   17 points');
   gotoxy(20,7);
   write(' 2. Williams Renault   10 points');
   gotoxy(20,8);
   write('    Benetton Renault   10 points');
   gotoxy(20,9);
   write(' 4. Ferrari             8 points');
   gotoxy(20,10);
   write(' 5. Prost-Mugen Honda   6 points');
   gotoxy(20,11);
   write(' 6. Sauber Petronas     1 point ');
  end;
  14:goto sf;
 end;
 gotoxy(20,25);
 write('Press "ENTER" to return to previous menu.');
 readln;
 goto a1;
 sf:
end;

Procedure argentina;
label a1,sf;
var a:byte;
begin
 a1:
 clrscr;
 atribuire;
 meniu(cuv,8,a);
 textbackground(black);
 textcolor(red);
 clrscr;
 case a of
  7:
  begin
   gotoxy(10,4);
   write('Date of the competition this year : 13.04.1997');
   gotoxy(10,6);
   write('Track length : 4.260 Km');
   gotoxy(10,8);
   write('Number of laps : 72');
   gotoxy(10,10);
   write('Total length : 306.72 Km');
   gotoxy(10,12);
   write('First used by FIA in the World Championship : 1952');
  end;
  8:
  begin
   textcolor(blue);
   gotoxy(12,2);
   write('ARGENTINIAN GRAND PRIX - QUALIFING TIMES - 12.04.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' 1.  Jacques Villeneuve     Williams Renault   CAN   1:24:473');
   writeln(' 2.  Heinz-Harald Frentzen  Williams Renault   GER   1:25:271');
   writeln(' 3.  Olivier Panis 2        Prost-Mugen Honda  FRA   1:25:491');
   writeln(' 4.  Michael Schumacher     Ferrari            GER   1:25:773');
   writeln(' 5.  Rubens Barrichello     Stewart Ford       BRA   1:25:932');
   writeln(' 6.  Ralf Schumacher        Jordan Peugeot     GER   1:26:218');
   writeln(' 7.  Eddie Irvine           Ferrari            GBR   1:26:327');
   writeln(' 8.  Johnny Herbert         Sauber Petronas    GBR   1:26:564');
   writeln(' 9.  Giancarlo Fisichella   Jordan Peugeot     ITA   1:26:619');
   writeln('10.  David Coulthard        McLaren Mercedes   GBR   1:26:799');
   writeln('11.  Jean Alesi             Benetton Renault   FRA   1:27:076');
   writeln('12.  Gerhard Berger         Benetton Renault   AUT   1:27:259');
   writeln('13.  Damon Hill             Arrows Yamaha      GBR   1:27:281');
   writeln('14.  Nicola Larini          Sauber Petronas    ITA   1:27:690');
   writeln('15.  Jan Magnussen          Stewart Ford       DAN   1:28:035');
   writeln('16.  Jos Verstappen         Tyrrell Ford       NED   1:28:094');
   writeln('17.  Mika Hakkinen          McLaren Mercedes   FIN   1:28:135');
   writeln('18.  Jarno Trulli           Minardi Hart       ITA   1:28:160');
   writeln('19.  Mika Salo              Tyrrell Ford       FIN   1:28:224');
   writeln('20.  Shinji Nakano          Prost-Mugen Honda  JAP   1:28:366');
   gotoxy(20,25);
   write('Press "ENTER" for the following places.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(12,2);
   write('ARGENTINIAN GRAND PRIX - QUALIFING TIMES - 12.04.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln('21.  Ukyo Katayama          Minardi Hart       JAP   1:28:413');
   writeln('22.  Pedro Diniz            Arrows Yamaha      BRA   1:28:969');
  end;
  9:
  begin
   textcolor(blue);
   gotoxy(12,2);
   write('ARGENTINIAN GRAND PRIX - RACE FINISHING TIMES - 13.04.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' 1.  Jacques Villeneuve     Williams Renault   CAN   1h:52:01:715');
   writeln(' 2.  Eddie Irvine           Ferrarri           GBR         +0:979');
   writeln(' 3.  Ralf Schumacher        Jordan Peugeot     GER        +12:089');
   writeln(' 4.  Johnny Herbert         Sauber Petronas    GBR        +29:919');
   writeln(' 5.  Mika Hakkinen          McLaren Mercedes   FIN        +30:351');
   writeln(' 6.  Gerhard Berger         Benetton Renault   AUT        +31:393');
   writeln(' 7.  Jean Alesi             Benetton Renault   FRA        +46:359');
   writeln(' 8.  Mika Salo              Tyrrell Ford       FIN         +1 lap');
   writeln(' 9.  Jarno Trulli           Minardi Hart       ITA         +1 lap');
   writeln('10.  Jan Magnussen          Stewart Ford       DAN        +5 laps');
   writeln;
   textcolor(blue);
   writeln('                           NOT CLASSIFIED');
   writeln;
   textcolor(red);
   writeln(' NC  Damon Hill             Arrows Yamaha      GBR     -');
   writeln(' NC  Pedro Diniz            Arrows Yamaha      BRA     -');
   writeln(' NC  Heinz-Harald Frentzen  Williams Renault   GER     -');
   writeln(' NC  Michael Schumacher     Ferrari            GER     -');
   writeln(' NC  David Coulthard        McLaren Mercedes   GBR     -');
   writeln(' NC  Giancarlo Fisichella   Jordan Peugeot     ITA     -');
   writeln(' NC  Olivier Panis          Prost-Mugen Honda  FRA     -');
   gotoxy(20,25);
   write('Press "ENTER" for the following places.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(12,2);
   write('ARGENTINIAN GRAND PRIX - RACE FINISHING TIMES - 13.04.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' NC  Shinji Nakano          Prost-Mugen Honda  JAP     -');
   writeln(' NC  Nicola Larini          Sauber Petronas    ITA     -');
   writeln(' NC  Jos Verstappen         Tyrrell Ford       NED     -');
   writeln(' NC  Ukyo Katayama          Minardi Hart       JAP     -');
   writeln(' NC  Rubens Barrichello     Stewart Ford       BRA     -');
  end;
  10:
  begin
   gotoxy(10,4);
   write('Fastest lap : ');
   gotoxy(10,6);
   write('Gerhard Berger          Benetton Renault   1:27:981');
  end;
  11:
  begin
   winners('Jacques Villeneuve','Eddie Irvine','Ralf Schumacher');
   readln;
   closegraph;
   goto a1;
  end;
  12:
  begin
   textcolor(blue);
   gotoxy(15,4);
   write('DRIVERS CHAMPIONSHIP - AFTER ARGENTINIAN GP');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. Jacques Villeneuve     10 points');
   gotoxy(20,7);
   write(' 2. Eddie Irvine            6 points');
   gotoxy(20,8);
   write(' 3. Ralf Schumacher         4 points');
   gotoxy(20,9);
   write(' 4. Johnny Herbert          3 points');
   gotoxy(20,10);
   write(' 5. Mika Hakkinen           2 points');
   gotoxy(20,11);
   write(' 6. Gerhard Berger          1 point ');
   gotoxy(20,25);
   write('Press "ENTER" to view the overall classification.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(15,4);
   write('DRIVERS CHAMPIONSHIP - OVERALL');
   gotoxy(20,6);
   textcolor(red);
   write(' 1. Jacques Villeneuve     20 points');
   gotoxy(20,7);
   write(' 2. David Coulthard        10 points');
   gotoxy(20,8);
   write('    Gerhard Berger         10 points');
   gotoxy(20,9);
   write(' 4. Mika Hakkinen           9 points');
   gotoxy(20,10);
   write(' 5. Michael Schumacher      8 points');
   gotoxy(20,11);
   write(' 6. Olivier Panis           6 points');
   gotoxy(20,12);
   write('    Eddie Irvine            6 points');
   gotoxy(20,13);
   write(' 8. Ralf Schumacher         4 points');
   gotoxy(20,14);
   write(' 9. Johnny Herbert          3 points');
   gotoxy(20,15);
   write('10. Jean Alesi              1 point ');
   gotoxy(20,16);
   write('    Nicola Larini           1 point ');
  end;
  13:
  begin
   textcolor(blue);
   gotoxy(15,4);
   write('CONSTRUCTORS CHAMPIONSHIP - AFTER ARGENTINIAN GP');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. Williams Renault   10 points');
   gotoxy(20,7);
   write(' 2. Ferrari             6 points');
   gotoxy(20,8);
   write(' 3. Jordan Peugeot      4 points');
   gotoxy(20,9);
   write(' 4. Sauber Petronas     3 points');
   gotoxy(20,10);
   write(' 5. McLaren Mercedes    2 points');
   gotoxy(20,11);
   write(' 6. Benetton Renault    1 point ');
   gotoxy(20,25);
   write('Press "ENTER" to view the overall classification.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(15,4);
   write('CONSTRUCTORS CHAMPIONSHIP - OVERALL');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. Williams Renault   20 points');
   gotoxy(20,7);
   write(' 2. McLaren Mercedes   19 points');
   gotoxy(20,8);
   write(' 3. Ferrari            14 points');
   gotoxy(20,9);
   write(' 4. Benetton Renault   11 points');
   gotoxy(20,10);
   write(' 5. Prost-Mugen Honda   6 points');
   gotoxy(20,11);
   write(' 6. Jordan Peugeot      4 point ');
   gotoxy(20,12);
   write('    Sauber Petronas     4 point ');
  end;
  14:goto sf;
 end;
 gotoxy(20,25);
 write('Press "ENTER" to return to previous menu.');
 readln;
 goto a1;
 sf:
end;

Procedure san_marino;
label a1,sf;
var a:byte;
begin
 a1:
 clrscr;
 atribuire;
 meniu(cuv,8,a);
 textbackground(black);
 textcolor(red);
 clrscr;
 case a of
  7:
  begin
   gotoxy(10,4);
   write('Date of the competition this year : 27.04.1997');
   gotoxy(10,6);
   write('Track length : 4.892 Km');
   gotoxy(10,8);
   write('Number of laps : 63');
   gotoxy(10,10);
   write('Total length : 308.196 Km');
  end;
  8:
  begin
   textcolor(blue);
   gotoxy(12,2);
   write('SAN MARINO GRAND PRIX - QUALIFING TIMES - 26.04.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' 1.  Jacques Villeneuve     Williams Renault   CAN   1:23:303');
   writeln(' 2.  Heinz-Harald Frentzen  Williams Renault   GER   1:23:646');
   writeln(' 3.  Michael Scumacher      Ferrari            GER   1:23:955');
   writeln(' 4.  Olivier Panis          Prost-Mugen Honda  FRA   1:24:075');
   writeln(' 5.  Ralf Schumacher        Jordan Peugeot     GER   1:24:081');
   writeln(' 6.  Giancarlo Fisichella   Jordan Peugeot     ITA   1:24:596');
   writeln(' 7.  Johnny Herbert         Sauber Petronas    GBR   1:24:723');
   writeln(' 8.  Mika Hakkinen          McLaren Mercedes   FIN   1:24:812');
   writeln(' 9.  Eddie Irvine           Ferrari            GBR   1:24:861');
   writeln('10.  David Coulthard        McLaren Mercedes   GBR   1:25:077');
   writeln('11.  Gerhard Berger         Benetton Renault   AUT   1:25:371');
   writeln('12.  Nicola Larini          Sauber Petronas    ITA   1:25:544');
   writeln('13.  Rubens Barrichello     Stewart Ford       BRA   1:25:579');
   writeln('14.  Jean Alesi             Benetton Renault   FRA   1:25:729');
   writeln('15.  Damon Hill             Arrows Yamaha      GBR   1:25:743');
   writeln('16.  Jan Magnussen          Stewart Ford       DEN   1:26:192');
   writeln('17.  Pedro Diniz            Arrows Yamaha      GBR   1:26:253');
   writeln('18.  Shinji Nakano          Prost-Mugen Honda  JAP   1:26:712');
   writeln('19.  Mika Salo              Tyrrell Ford       FIN   1:26:852');
   writeln('20.  Jarno Trulli           Minardi Hart       ITA   1:26:960');
   gotoxy(20,25);
   write('Press "ENTER" for the following places.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(12,2);
   write('SAN MARINO GRAND PRIX - QUALIFING TIMES - 26.04.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln('21.  Jos Verstappen         Tyrrell Ford       NED   1:27:428');
   writeln('22.  Ukyo Katayama          Minardi Hart       JAP   1:28:727');
  end;
  9:
  begin
   textcolor(blue);
   gotoxy(12,2);
   write('SAN MARINO GRAND PRIX - RACE FINISHING TIMES - 27.04.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' 1.  Heinz-Harald Frentzen  Williams Renault   GER   1h:31:00:673');
   writeln(' 2.  Michael Schumacher     Ferrari            GER         +1:237');
   writeln(' 3.  Eddie Irvine           Ferrari            GBR      +1:18:343');
   writeln(' 4.  Giancarlo Fisichella   Jordan Peugeot     ITA      +1:24:075');
   writeln(' 5.  Jean Alesi             Benetton Renault   FRA         +1 lap');
   writeln(' 6.  Mika Hakkinen          McLaren Mercedes   FIN         +1 lap');
   writeln(' 7.  Nicola Larini          Sauber Petronas    ITA         +1 lap');
   writeln(' 8.  Olivier Panis          Prost-Mugen Honda  FRA         +1 lap');
   writeln(' 9.  Mika Salo              Tyrrell Ford       FIN        +2 laps');
   writeln('10.  Jos Verstappen         Tyrrell Ford       NED        +2 laps');
   writeln('11.  Ukyo Katayama          Minardi Hart       JAP        +3 laps');
   writeln;
   textcolor(blue);
   writeln('                           NOT CLASSIFIED');
   writeln;
   textcolor(red);
   writeln(' NC  Damon Hill             Arrows Yamaha      GBR     -');
   writeln(' NC  Pedro Diniz            Arrows Yamaha      BRA     -');
   writeln(' NC  Jacques Villeneuve     Williams Renault   CAN     -');
   writeln(' NC  Gerhard Berger         Benetton Renault   AUT     -');
   writeln(' NC  David Coulthard        McLaren Mercedes   GBR     -');
   writeln(' NC  Ralf Schumacher        Jordan Peugeot     GER     -');
   gotoxy(20,25);
   write('Press "ENTER" for the following places.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(12,2);
   write('SAN MARINO GRAND PRIX - RACE FINISHING TIMES - 27.04.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' NC  Shinji Nakano          Prost-Mugen Honda  JAP     -');
   writeln(' NC  Johnny Herbert         Sauber Petronas    GBR     -');
   writeln(' NC  Jarno Trulli           Minardi Hart       ITA     -');
   writeln(' NC  Rubens Barrichello     Stewart Ford       BRA     -');
   writeln(' NC  Jan Magnussen          Stewart Ford       DEN     -');
  end;
  10:
  begin
   gotoxy(10,4);
   write('Fastest lap : ');
   gotoxy(10,6);
   write('Heinz-Harald Frentzen   Willams Renault    1:25:531');
  end;
  11:
  begin
   winners('Heinz-Harald Frentzen','Michael Scumacher','Eddie Irvine');
   readln;
   closegraph;
   goto a1;
  end;
  12:
  begin
   textcolor(blue);
   gotoxy(15,4);
   write('DRIVERS CHAMPIONSHIP - AFTER SAN MARINO GP');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. Heinz-Harald Frentzen  10 points');
   gotoxy(20,7);
   write(' 2. Michael Schumacher      6 points');
   gotoxy(20,8);
   write(' 3. Eddie Irvine            4 points');
   gotoxy(20,9);
   write(' 4. Giancarlo Fisichella    3 points');
   gotoxy(20,10);
   write(' 5. Jean Alesi              2 points');
   gotoxy(20,11);
   write(' 6. Mika Hakkinen           1 point ');
   gotoxy(20,25);
   write('Press "ENTER" to view the overall classification.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(15,4);
   write('DRIVERS CHAMPIONSHIP - OVERALL');
   gotoxy(20,6);
   textcolor(red);
   write(' 1. Jacques Villeneuve     20 points');
   gotoxy(20,7);
   write(' 2. Michael Schumacher     14 points');
   gotoxy(20,8);
   write(' 3. Gerhard Berger         10 points');
   gotoxy(20,9);
   write('    Mika Hakkinen          10 points');
   gotoxy(20,10);
   write('    David Coulthard        10 points');
   gotoxy(20,11);
   write('    Eddie Irvine           10 points');
   gotoxy(20,12);
   write('    Heinz-Harald Frentzen  10 points');
   gotoxy(20,13);
   write(' 8. Olivier Panis           6 points');
   gotoxy(20,14);
   write(' 9. Ralf Schumacher         4 points');
   gotoxy(20,15);
   write('10. Johnny Herbert          3 points');
   gotoxy(20,16);
   write('    Giancarlo Fisichella    3 points');
   gotoxy(20,17);
   write('    Jean Alesi              3 points');
   gotoxy(20,18);
   write('13. Nicola Larini           1 point ');
   write
  end;
  13:
  begin
   textcolor(blue);
   gotoxy(15,4);
   write('CONSTRUCTORS CHAMPIONSHIP - AFTER SAN MARINO GP');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. Williams Renault   10 points');
   gotoxy(20,7);
   write(' 2. Ferrari            10 points');
   gotoxy(20,8);
   write(' 3. Jordan Peugeot      3 points');
   gotoxy(20,9);
   write(' 4. Benetton Renault    2 points');
   gotoxy(20,10);
   write(' 5. McLaren Mercedes    1 point ');
   gotoxy(20,25);
   write('Press "ENTER" to view the overall classification.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(15,4);
   write('CONSTRUCTORS CHAMPIONSHIP - OVERALL');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. Williams Renault   30 points');
   gotoxy(20,7);
   write(' 2. Ferrari            24 points');
   gotoxy(20,8);
   write(' 3. McLaren Mercedes   20 points');
   gotoxy(20,9);
   write(' 4. Benetton Renault   13 points');
   gotoxy(20,10);
   write(' 5. Jordan Peugeot      7 points');
   gotoxy(20,11);
   write(' 6. Prost-Mugen Honda   6 points');
   gotoxy(20,12);
   write(' 7. Sauber Petronas     4 points');
  end;
  14:goto sf;
 end;
 gotoxy(20,25);
 write('Press "ENTER" to return to previous menu.');
 readln;
 goto a1;
 sf:
end;

Procedure monte_carlo;
label a1,sf;
var a:byte;
begin
 a1:
 clrscr;
 atribuire;
 meniu(cuv,8,a);
 textbackground(black);
 textcolor(red);
 clrscr;
 case a of
  7:
  begin
   gotoxy(10,4);
   write('Date of the competition this year : 11.05.1997');
   gotoxy(10,6);
   write('Track length : 3.367 Km');
   gotoxy(10,8);
   write('Number of laps : 78');
   gotoxy(10,10);
   write('Total length : 262.626 Km');
  end;
  8:
  begin
   textcolor(blue);
   gotoxy(12,2);
   write('MONTE CARLO GRAND PRIX - QUALIFING TIMES - 10.05.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' 1.  Heinz-Harald Frentzen  Williams Renault   GER   1:18:216');
   writeln(' 2.  Michael Scumacher      Ferrari            GER   1:18:235');
   writeln(' 3.  Jacques Villeneuve     Williams Renault   CAN   1:18:583');
   writeln(' 4.  Giancarlo Fisichella   Jordan Peugeot     ITA   1:18:665');
   writeln(' 5.  David Coulthard        McLaren Mercedes   GBR   1:18:779');
   writeln(' 6.  Ralf Scumacher         Jordan Peugeot     GER   1:18:943');
   writeln(' 7.  Johnny Herbert         Sauber Petronas    GBR   1:19:105');
   writeln(' 8.  Mika Hakkinen          McLaren Mercedes   FIN   1:19:119');
   writeln(' 9.  Jean Alesi             Benetton Renault   FRA   1:19:263');
   writeln('10.  Rubens Barrichello     Stewart Ford       BRA   1:19:295');
   writeln('11.  Nicola Larini          Sauber Petronas    ITA   1:19:668');
   writeln('12.  Olivier Panis          Prost-Mugen Honda  FRA   1:19:626');
   writeln('13.  Damon Hill             Arrows Yamaha      GBR   1:19:674');
   writeln('14.  Mika Salo              Tyrrell Ford       FIN   1:19:694');
   writeln('15.  Eddie Irvine           Ferrari            GBR   1:19:723');
   writeln('16.  Pedro Diniz            Arrows Yamaha      BRA   1:19:860');
   writeln('17.  Gerhard Berger         Benetton Renault   AUT   1:20:199');
   writeln('18.  Jarno Trulli           Minardi Hart       ITA   1:20:349');
   writeln('19.  Jan Magnussen          Stewart Ford       DEN   1:20:516');
   writeln('20.  Ukyo Katayama          Minardi Hart       JAP   1:20:606');
   gotoxy(20,25);
   write('Press "ENTER" for the following places.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(12,2);
   write('SAN MARINO GRAND PRIX - QUALIFING TIMES - 10.05.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln('21.  Shinji Nakano          Prost-Mugen Honda  JAP   1:20:961');
   writeln('22.  Jos Verstappen         Tyrrell Ford       NED   1:21:290');
  end;
  9:
  begin
   textcolor(blue);
   gotoxy(12,2);
   write('MONTE CARLO GRAND PRIX - RACE FINISHING TIMES - 11.05.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' 1.  Michael Schumacher     Ferrari            GER   2h:00:00:000');
   writeln(' 2.  Rubens Barrichello     Stewart Ford       BRA        +53:306');
   writeln(' 3.  Eddie Irvine           Ferrari            GBR      +1:22:108');
   writeln(' 4.  Olivier Panis          Prost-Mugen Honda  FRA      +1:44:402');
   writeln(' 5.  Mika Salo              Tyrrell Ford       FIN         +1 lap');
   writeln(' 6.  Giancarlo Fisichella   Jordan Peugeot     ITA         +1 lap');
   writeln(' 7.  Jan Magnussen          Stewart Ford       DEN         +1 lap');
   writeln(' 8.  Jos Verstappen         Tyrrell Ford       NED        +2 laps');
   writeln(' 9.  Gerhard Berger         Benetton Renault   AUT        +2 laps');
   writeln('10.  Ukyo Katayama          Minardi Hart       JAP        +2 laps');
   writeln;
   textcolor(blue);
   writeln('                           NOT CLASSIFIED');
   writeln;
   textcolor(red);
   writeln(' NC  Damon Hill             Arrows Yamaha      GBR     -');
   writeln(' NC  Pedro Diniz            Arrows Yamaha      BRA     -');
   writeln(' NC  Jacques Villeneuve     Williams Renault   CAN     -');
   writeln(' NC  Heinz-Harlad Frentzen  Williams Renault   GER     -');
   writeln(' NC  Jean Alesi             Benetton Renault   FRA     -');
   writeln(' NC  Mika Hakkinen          McLaren Mercedes   FIN     -');
   writeln(' NC  David Coulthard        McLaren Mercedes   GBR     -');
   gotoxy(20,25);
   write('Press "ENTER" for the following places.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(12,2);
   write('MONTE CARLO GRAND PRIX - RACE FINISHING TIMES - 11.05.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' NC  Ralf Schumacher        Jordan Peugeot     GER     -');
   writeln(' NC  Shinji Nakano          Prost-Mugen Honda  JAP     -');
   writeln(' NC  Johnny Herbert         Sauber Petronas    GBR     -');
   writeln(' NC  Nicola Larini          Sauber Petronas    ITA     -');
   writeln(' NC  Jarno Trulli           Minardi Hart       ITA     -');
  end;
  10:
  begin
   gotoxy(10,4);
   write('Fastest lap : ');
   gotoxy(10,6);
   write('Michael Scumacher       Ferrari            1:53:315');
  end;
  11:
  begin
   winners('Michael Scumacher','Rubens Barrichello','Eddie Irvine');
   readln;
   closegraph;
   goto a1;
  end;
  12:
  begin
   textcolor(blue);
   gotoxy(15,4);
   write('DRIVERS CHAMPIONSHIP - AFTER MONTE CARLO GP');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. Michael Scumacher      10 points');
   gotoxy(20,7);
   write(' 2. Rubens Barrichello      6 points');
   gotoxy(20,8);
   write(' 3. Eddie Irvine            4 points');
   gotoxy(20,9);
   write(' 4. Olivier Panis           3 points');
   gotoxy(20,10);
   write(' 5. Mika Salo               2 points');
   gotoxy(20,11);
   write(' 6. Giancarlo Fisichella    1 point ');
   gotoxy(20,25);
   write('Press "ENTER" to view the overall classification.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(15,4);
   write('DRIVERS CHAMPIONSHIP - OVERALL');
   gotoxy(20,6);
   textcolor(red);
   write(' 1. Michael Scumacher      24 points');
   gotoxy(20,7);
   write(' 2. Jacques Villeneuve     20 points');
   gotoxy(20,8);
   write(' 3. Eddie Irvine           14 points');
   gotoxy(20,9);
   write(' 4. Gerhard Berger         10 points');
   gotoxy(20,10);
   write('    Mika Hakkinen          10 points');
   gotoxy(20,11);
   write('    David Coulthard        10 points');
   gotoxy(20,12);
   write('    Heinz-Harald Frentzen  10 points');
   gotoxy(20,13);
   write(' 8. Olivier Panis           9 points');
   gotoxy(20,14);
   write(' 9. Rubens Barichello       6 points');
   gotoxy(20,15);
   write('10. Giancarlo Fisichella    4 points');
   gotoxy(20,16);
   write('    Ralf Scumacher          4 points');
   gotoxy(20,17);
   write('12. Johnny Herbert          3 points');
   gotoxy(20,18);
   write('    Jean Alesi              3 points');
   gotoxy(20,19);
   write('14. Mika Salo               2 points');
   gotoxy(20,20);
   write('15. Nicola Larini           1 point ');
  end;
  13:
  begin
   textcolor(blue);
   gotoxy(15,4);
   write('CONSTRUCTORS CHAMPIONSHIP - AFTER MONTE CARLO GP');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. Ferrari            14 points');
   gotoxy(20,7);
   write(' 2. Stewart Ford        6 points');
   gotoxy(20,8);
   write(' 3. Prost-Mugen Honda   3 points');
   gotoxy(20,9);
   write(' 4. Tyrrell Ford        2 points');
   gotoxy(20,10);
   write(' 5. Jordan Peugeot      1 point ');
   gotoxy(20,25);
   write('Press "ENTER" to view the overall classification.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(15,4);
   write('CONSTRUCTORS CHAMPIONSHIP - OVERALL');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. Ferrari            38 points');
   gotoxy(20,7);
   write(' 2. Williams Renault   30 points');
   gotoxy(20,8);
   write(' 3. McLaren Mercedes   20 points');
   gotoxy(20,9);
   write(' 4. Benetton Renault   13 points');
   gotoxy(20,10);
   write(' 5. Prost-Mugen Honda   9 points');
   gotoxy(20,11);
   write(' 6. Jordan Peugeot      8 points');
   gotoxy(20,12);
   write(' 7. Stewart Ford        6 points');
   gotoxy(20,13);
   write(' 8. Sauber Petronas     4 points');
   gotoxy(20,14);
   write(' 9. Tyrrell Ford        2 points');
  end;
  14:goto sf;
 end;
 gotoxy(20,25);
 write('Press "ENTER" to return to previous menu.');
 readln;
 goto a1;
 sf:
end;

{Procedure spain;
label a1,sf;
var a:byte;
begin
 a1:
 clrscr;
 atribuire;
 meniu(cuv,8,a);
 textbackground(black);
 textcolor(red);
 clrscr;
 case a of
  7:
  begin
   gotoxy(10,4);
   write('Date of the competition this year : 25.05.1997');
   gotoxy(10,6);
   write('Track length : 4.727 Km');
   gotoxy(10,8);
   write('Number of laps : 65');
   gotoxy(10,10);
   write('Total length : 307.255 Km');
   gotoxy(10,12);
   write('First used by FIA in the World Championship : 1991');
  end;
  8:
  begin
   textcolor(blue);
   gotoxy(12,2);
   write('SPAIN GRAND PRIX - QUALIFING TIMES - 24.05.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' 1.  Jacques Villeneuve     Williams Renault   CAN   1:16:525');
   writeln(' 2.  Heinz-Harald Frentzen  Williams Renault   GER   1:16:791');
   writeln(' 3.  David Coulthard        McLaren Mercedes   GBR   1:17:521');
   writeln(' 4.  Jean Alesi             Benetton Renault   FRA   1:17:717');
   writeln(' 5.  Mika Hakkinen          McLaren Mercedes   GBR   1:17:737');
   writeln(' 6.  Gerhard Berger         Benetton Renault   AUT   1:18:041');
   writeln(' 7.  Michael Scumacher      Ferrari            GER   1:18:313');
   writeln(' 8.  Giancarlo Fisichella   Jordan Peugeot     ITA   1:18:385');
   writeln(' 9.  Ralf Scumacher         Jordan Peugeot     GER   1:18:423');
   writeln('10.  Johnny Herbert         Sauber Petronas    GBR   1:18:494');
   writeln('11.  Eddie Irvine           Ferrari            GBR   1:18:873');
   writeln('12.  Olivier Panis          Prost-Mugen Honda  FRA   1:19:157');
   writeln('13.  Gianni Morbidelli      Sauber Petronas    ITA   1:19:323');
   writeln('14.  Mika Salo              Tyrrell Ford       FIN   1:20:079');
   writeln('15.  Damon Hill             Arrows Yamaha      GBR   1:20:089');
   writeln('16.  Shinji Nakano          Prost-Mugen Honda  JAP   1:20:103');
   writeln('17.  Rubens Barichello      Stewart Ford       BRA   1:20:255');
   writeln('18.  Jarno Trulli           Minardi Hart       ITA   1:20:452');
   writeln('19.  Jos Verstappen         Tyrrell Ford       NED   1:20:582');
   writeln('20.  Ukyo Katayama          Minardi Hart       JAP   1:20:672');
   gotoxy(20,25);
   write('Press "ENTER" for the following places.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(12,2);
   write('SPAIN GARND PRIX - QUALIFING TIMES - 24.05.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln('21.  Pedro Diniz            Arrows Yamaha      BRA   1:21:029');
   writeln('22.  Jan Magnussen          Stewart Ford       DEN   1:21:290');
  end;
  9:
  begin
   textcolor(blue);
   gotoxy(12,2);
   write('SPAIN GRAND PRIX - RACE FINISHING TIMES - 25.05.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' 1.  Jacques Villeneuve     Williams Renault   CAN   1h:30:35:896');
   writeln(' 2.  Olivier Panis          Prost-Mugen Honda  FRA         +5:804');
   writeln(' 3.  Jean Alesi             Benetton Renault   FRA        +12:534');
   writeln(' 4.  Michael Scumacher      Ferrari            GER        +17:997');
   writeln(' 5.  Johnny Herbert         Sauber Petronas    GBR        +27:986');
   writeln(' 6.  David Coulthard        McLaren Mercedes   GBR        +29:774');
   writeln(' 7.  Mika Hakkinen          McLaren Mercedes   FIN        +48:785');
   writeln(' 8.  Heinz-Harald Frentzen  Williams Renault   GER      +1:04:139');
   writeln(' 9.  Giancarlo Fisichella   Jordan Peugeot     ITA      +1:04:767');
   writeln('10.  Gerhard Berger         Benetton Renault   AUT      +1:05:670');
   writeln('11.  Jos Verstappen         Tyrrell Ford       NED         +1 lap');
   writeln('12.  Eddie Irvine           Ferrari            GBR         +1 lap');
   writeln('13.  Jan Magnussen          Stewart Ford       DEN         +1 lap');
   writeln('14.  Gianni Morbidelli      Sauber Petronas    ITA        +2 laps');
   writeln('15.  Jarno Trulli           Minardi Hart       ITAc       +2 laps');
   writeln;
   textcolor(blue);
   writeln('                           NOT CLASSIFIED');
   writeln;
   textcolor(red);
   writeln(' NC  Damon Hill             Arrows Yamaha      GBR     -');
   writeln(' NC  Pedro Diniz            Arrows Yamaha      BRA     -');
   gotoxy(20,25);
   write('Press "ENTER" for the following places.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(12,2);
   write('SPAIN GRAND PRIX - RACE FINISHING TIMES - 25.05.1997');
   textcolor(red);
   gotoxy(1,4);
   writeln('Nr.  Name                   Team               Nat.  Time');
   writeln(' NC  Ralf Schumacher        Jordan Peugeot     GER     -');
   writeln(' NC  Shinji Nakano          Prost-Mugen Honda  JAP     -');
   writeln(' NC  Mika Salo              Tyrrell Ford       FIN     -');
   writeln(' NC  Ukyo Katayama          Minardi Hart       JAP     -');
   writeln(' NC  Rubens Barichello      Stewart Ford       BRA     -');
  end;
  10:
  begin
   gotoxy(10,4);
   write('Fastest lap : ');
   gotoxy(10,6);
   write('Giancarlo Fisichella    Jordan Peugeot     1:22:246');
  end;
  11:
  begin
   winners('Jacques Villeneuve','Olivier Panis','Jean Alesi');
   readln;
   closegraph;
   goto a1;
  end;
  12:
  begin
   textcolor(blue);
   gotoxy(15,4);
   write('DRIVERS CHAMPIONSHIP - AFTER SPAIN GP');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. Jacques Villeneuve     10 points');
   gotoxy(20,7);
   write(' 2. Olivier Panis           6 points');
   gotoxy(20,8);
   write(' 3. Jean Alesi              4 points');
   gotoxy(20,9);
   write(' 4. Michael Scumacher       3 points');
   gotoxy(20,10);
   write(' 5. Johnny Herbert          2 points');
   gotoxy(20,11);
   write(' 6. David Coulthard         1 point ');
   gotoxy(20,25);
   write('Press "ENTER" to view the overall classification.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(15,4);
   write('DRIVERS CHAMPIONSHIP - OVERALL');
   gotoxy(20,6);
   textcolor(red);
   write(' 1. Jacques Villeneuve     30 points');
   gotoxy(20,7);
   write(' 2. Michael Scumacher      27 points');
   gotoxy(20,8);
   write(' 3. Olivier Panis          15 points');
   gotoxy(20,9);
   write(' 4. Eddie Irvine           14 points');
   gotoxy(20,10);
   write(' 5. David Coulthard        11 points');
   gotoxy(20,11);
   write(' 6. Gerhard Berger         10 points');
   gotoxy(20,12);
   write('    Mika Hakkinen          10 points');
   gotoxy(20,13);
   write('    Heinz-Harald Frentzen  10 points');
   gotoxy(20,14);
   write(' 9. Jean Alesi              7 points');
   gotoxy(20,15);
   write('10. Rubens Barichello       6 points');
   gotoxy(20,16);
   write('11. Johnny Herbert          5 points');
   gotoxy(20,17);
   write('12. Giancarlo Fisichella    4 points');
   gotoxy(20,18);
   write('    Ralf Scumacher          4 points');
   gotoxy(20,19);
   write('14. Mika Salo               2 points');
  end;
  13:
  begin
   textcolor(blue);
   gotoxy(15,4);
   write('CONSTRUCTORS CHAMPIONSHIP - AFTER SPAIN GP');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. Williams Renault   10 points');
   gotoxy(20,7);
   write(' 2. Prost-Mugen Honda   6 points');
   gotoxy(20,8);
   write(' 3. Benetton Renault    4 points');
   gotoxy(20,9);
   write(' 4. Ferrari             3 points');
   gotoxy(20,10);
   write(' 5. Sauber Petronas     2 points');
   gotoxy(20,11);
   write(' 6. McLaren Mercedes    1 point ');
   gotoxy(20,25);
   write('Press "ENTER" to view the overall classification.');
   readln;
   clrscr;
   textcolor(blue);
   gotoxy(15,4);
   write('CONSTRUCTORS CHAMPIONSHIP - OVERALL');
   textcolor(red);
   gotoxy(20,6);
   write(' 1. Ferrari            41 points');
   gotoxy(20,7);
   write(' 2. Williams Renault   40 points');
   gotoxy(20,8);
   write(' 3. McLaren Mercedes   21 points');
   gotoxy(20,9);
   write(' 4. Benetton Renault   17 points');
   gotoxy(20,10);
   write(' 5. Prost-Mugen Honda  15 points');
   gotoxy(20,11);
   write(' 6. Jordan Peugeot      8 points');
   gotoxy(20,12);
   write(' 7. Stewart Ford        6 points');
   gotoxy(20,13);
   write('    Sauber Petronas     6 points');
   gotoxy(20,14);
   write(' 9. Tyrrell Ford        2 points');
  end;
  14:goto sf;
 end;
 gotoxy(20,25);
 write('Press "ENTER" to return to previous menu.');
 readln;
 goto a1;
 sf:
end;}

begin
 ini;
 setbkcolor(lightgreen);
 settextstyle(1,horizdir,4);
 setfillstyle(solidfill,yellow);
 setcolor(blue);
 for i:=0 to getmaxx do
  begin
   formula(i,red);
   sound(i+50);
   delay(20);
   formula(i,lightgreen);
   nosound;
  end;
 setfillstyle(solidfill,lightgreen);
 bar(0,217,4,257);
 setcolor(blue);
 setfillstyle(solidfill,yellow);
 bar(5,217,getmaxx-3,257);
 rectangle(5,217,getmaxx-3,257);
 outtextxy(5,217,'FORMULA ONE-GRAND PRIX-YEAR 1997');
 readln;
 closegraph;
 1:
 clrscr;
 textbackground(black);
 cuv[1]:='1997 - SCHEDULE';
 cuv[2]:='PILOTS & TEAMS';
 cuv[3]:='GRAND PRIX-S : INFO';
 cuv[4]:='EXIT THE PROGRAM';
 meniu(cuv,4,id);
 textbackground(black);
 textcolor(brown);
 if id=10 then
           begin
            textcolor(lightgray);
            clrscr;
            halt;
           end;
 if id=7 then
  begin
   schedule;
   goto 1;
  end;
 if id=8 then
  begin
   pilots_teams;
   goto 1;
  end;
 if id=9 then
  begin
   2:
   cuv[1]:='GP OF AUSTRALIA';
   cuv[2]:='GP OF BRAZIL';
   cuv[3]:='GP OF ARGENTINA';
   cuv[4]:='GP OF SAN MARINO';
   cuv[5]:='GP OF MONACO';
   cuv[6]:='GP OF SPAIN';
   cuv[7]:='GP OF CANADA';
   cuv[8]:='GP OF FRANCE';
   cuv[9]:='GP OF ENGLAND';
   cuv[10]:='GP OF GERMANY';
   cuv[11]:='GP OF HUNGARY';
   cuv[12]:='GP OF BELGIUM';
   cuv[13]:='GP OF ITALY';
   cuv[14]:='GP OF AUSTRY';
   cuv[15]:='GP OF LUXEMBOURG';
   cuv[16]:='GP OF JAPAN';
   cuv[17]:='GP OF PORTUGAL';
   cuv[18]:='PREVIOUS MENU';
   meniu(cuv,18,id);
   textbackground(black);
   case id of
     7:begin
        australia;
        textbackground(black);
        goto 2;
       end;
     8:begin
        brazilia;
        textbackground(black);
        goto 2;
       end;
     9:begin;
        argentina;
        textbackground(black);
        goto 2;
       end;
    10:begin
        san_marino;
        textbackground(black);
        goto 2;
       end;
    11:begin
        monte_carlo;
        textbackground(black);
        goto 2;
       end;
    12:begin
        {spain;}
        textbackground(black);
        goto 2;
       end;
    13,14,15,16,17,18,19,20,21,22,23:
             begin
              clrscr;
              textcolor(red);
              gotoxy(20,15);
              writeln('This Grand Prix hasn''t taken place yet.');
              gotoxy(20,25);
              writeln('Press "ENTER" to return to previous menu.');
              readln;
              goto 2;
             end;
    24:begin
        textbackground(black);
        goto 1;
       end;
   end;
  end;
 readln;
end.